/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.properties;

import com.j3d.ui.engine.FloatingPanel;
import com.j3d.ui.generic.J3DScrollBarUI;

import javax.swing.*;
import java.util.ArrayList;


/**
 *
 * @author yetnt
 */
public class PropertiesPanel extends javax.swing.JPanel {

    public FloatingPanel floatingPanel = new FloatingPanel("Properties Panel");

    /**
     * Creates new form PropertiesPanel
     */
    public PropertiesPanel() {
        initComponents();
        floatingPanel.finish(this, (c) -> {
            if (!(c instanceof PropertiesPanel lt)) return;
            lt.setBounds(0, 0, lt.getPreferredSize().width, lt.getPreferredSize().height);
            lt.setVisible(true);
//            lt.jScrollPane1.setBounds(0, 0, c.getPreferredSize().width, c.getPreferredSize().height);
//            JPanel prp = lt.propertiesPanel;
//            lt.propertiesPanel.setBounds(0, 0, prp.getPreferredSize().width, prp.getPreferredSize().height);
//            lt.setVisible(true);
//            lt.jScrollPane1.setVisible(true);
//            prp.setVisible(true);
        });
        J3DScrollBarUI.setBars(jScrollPane1);
    }

    public void toggleHidden() {
        floatingPanel.toggleHidden();
    }

    public void addAll(ArrayList<JPanel> panelArrayList) {
        panelArrayList.forEach(propertiesPanel::add);
        propertiesPanel.revalidate();
        propertiesPanel.setPreferredSize(null);
    }

    private static void debug(JPanel p, String name) {
        System.out.println(name);
        System.out.println("  pref = " + p.getPreferredSize());
        System.out.println("  min  = " + p.getMinimumSize());
        System.out.println("  max  = " + p.getMaximumSize());
        System.out.println("  size = " + p.getSize());
    }

    public void clear() {
        propertiesPanel.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertiesPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(412, 39));
        setMinimumSize(new java.awt.Dimension(412, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Da Properties Mf (here label specific)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setMinimumSize(new java.awt.Dimension(430, 265));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(430, 265));

        propertiesPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        propertiesPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        propertiesPanel.setLayout(new javax.swing.BoxLayout(propertiesPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(propertiesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel propertiesPanel;
    // End of variables declaration//GEN-END:variables
}
