/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.properties.panels;

import com.j3d.engine.react.actions.VoidAction;
import com.j3d.gen.properties.Property;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.function.Supplier;
import java.util.stream.Collectors;

import static com.j3d.Static.getPropertiesPanel;
import static com.j3d.engine.SceneManager.history;

/**
 *
 * @author yetnt
 */
public class BooleanProperty extends javax.swing.JPanel implements PropertyPanel<Boolean> {

    ArrayList<Property<Boolean, ?>> properties;

    /**
     * Creates new form StringProperty
     */
    public BooleanProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields();
    }

    @Override
    public void setFields() {
        if (singleProperty()) {
            enabledCheckbox.setText("Enabled");
            enabledCheckbox.setSelected(getSingleProperty().getValueSupplier().get());
            enabledCheckbox.setEnabled(!getSingleProperty().isConstant());
        } else {
            if (
                    getProperties().stream()
                            .anyMatch(Property::isConstant)
            )
                enabledCheckbox.setEnabled(false);
            if (allSameValue()) {
                enabledCheckbox.setSelected(getSingleProperty().getValueSupplier().get());
                enabledCheckbox.setText("Enabled (multiple)");
            } else {
                enabledCheckbox.setSelected(false);
                enabledCheckbox.setText("(multiple values)");
            }
        }
    }

    public boolean allSameValue() {
        int amt = getProperties().stream()
                .filter(p -> p.getValueSupplier().get())
                .toList().size();
        return amt == 0 || amt == getProperties().size();
    }

    @Override
    public ArrayList<Property<Boolean, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enabledCheckbox = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        enabledCheckbox.setText("Enabled");
        enabledCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(enabledCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enabledCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enabledCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledCheckboxActionPerformed
        VoidAction action = new VoidAction() {

            final LocalTime now = LocalTime.now();
            final Boolean value = enabledCheckbox.isSelected();
            final ArrayList<Boolean> oldValues = getProperties()
                    .stream()
                    .map(Property::getValueSupplier)
                    .map(Supplier::get)
                    .collect(Collectors.toCollection(ArrayList::new));

            @Override
            public Void run() {
                getProperties()
                        .forEach(p -> p.getNewValueConsumer().accept(value));
                setFields();
                getPropertiesPanel().repaint();
                return null;
            }

            @Override
            public void undo() {
                for (int i = 0; i < getProperties().size(); i++) {
                    Property<Boolean, ?> property = getProperties().get(i);
                    Boolean value = oldValues.get(i);
                    property.getNewValueConsumer().accept(value);
                }
                setFields();
                getPropertiesPanel().repaint();
            }

            @Override
            public boolean isReversible() {
                return true;
            }

            @Override
            public String getDescription() {
                return getActionDesc("Boolean", value);
            }

            @Override
            public LocalTime getTime() {
                return now;
            }
        };
        action.run();
        history.add(action);
    }//GEN-LAST:event_enabledCheckboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox enabledCheckbox;
    // End of variables declaration//GEN-END:variables
}
