/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.properties.panels;

import com.j3d.Static;
import com.j3d.gen.properties.Property;
import com.j3d.ui.generic.J3DTheme;
import com.j3d.utility.ClipboardUtil;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.UUID;

/**
 *
 * @author yetnt
 */
public class IDProperty extends javax.swing.JPanel implements PropertyPanel<UUID> {

    ArrayList<Property<UUID, ?>> properties;
    /**
     * Creates new form StringProperty
     */
    public IDProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields();
    }

    @Override
    public void setFields() {
        idTextField.setEnabled(false);
        if (singleProperty()) {
            idTextField.setText(
                    getSingleProperty().getValueSupplier()
                            .get().toString().substring(0, 15) + "..."
            );
            idTextField.addMouseListener(
                    new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            if (e.getClickCount() == 2) {
                                // add the UUID to the command palette
                                Static.commandParser.injectArgument(
                                        getSingleProperty().getValueSupplier().get()
                                );
                            }
                        }
                    }
            );
            // Ids should not be editable anyway
            // Really i should be consistent and check isCOnstant
            // but if im making an ID editable that's 100% a mistake.
//            if (getSingleProperty().isConstant())
//                idTextField.setEnabled(false);
        } else {
            idTextField.setText("(multiple)");
        }
    }

    @Override
    public ArrayList<Property<UUID, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextField = new javax.swing.JTextField();
        copyBtn = new javax.swing.JButton();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        idTextField.setEditable(false);
        idTextField.setBackground(J3DTheme.BACKGROUND.color());
        idTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        idTextField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        idTextField.setText("6f099092-2641-49b4...");
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        copyBtn.setBackground(J3DTheme.BACKGROUND.color());
        copyBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        copyBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        copyBtn.setText("copy");
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // not really anything meaningful here
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        // May as-well copy to user clipboard
        // TODO: Copies the first element. do something else
        ClipboardUtil.copyToClipboard(
                getSingleProperty().getValueSupplier().get().toString()
        );
    }//GEN-LAST:event_copyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyBtn;
    private javax.swing.JTextField idTextField;
    // End of variables declaration//GEN-END:variables
}
