/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.properties.panels;

import com.j3d.gen.properties.Property;

import java.util.ArrayList;

/**
 *
 * @author yetnt
 */
public class IntProperty extends javax.swing.JPanel implements PropertyPanel<Integer> {

    ArrayList<Property<Integer, ?>> properties;

    /**
     * Creates new form StringProperty
     */
    public IntProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields(); //TODO: Implement
    }

    @Override
    public void setFields() {

    }

    @Override
    public ArrayList<Property<Integer, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinner = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
