/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.properties.panels;

import com.j3d.engine.geometry.geo2d.graphics.GObject;
import com.j3d.gen.properties.Property;

import java.util.ArrayList;

/**
 *
 * @author yetnt
 */
public class ObjectProperty<T extends GObject> extends javax.swing.JPanel implements PropertyPanel<T> {

    ArrayList<Property<T, ?>> properties;
    /**
     * Creates new form StringProperty
     */
    public ObjectProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields(); //TODO: Implement
    }

    @Override
    public void setFields() {

    }

    @Override
    public ArrayList<Property<T, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copyBtn = new javax.swing.JButton();
        uuidTextField = new javax.swing.JTextField();
        labelTxtField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        copyBtn.setText("o");
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });

        uuidTextField.setEditable(false);
        uuidTextField.setText("6f099092....");

        labelTxtField.setEditable(false);
        labelTxtField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTxtField.setText("(point)");
        labelTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uuidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uuidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyBtn)
                    .addComponent(labelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTxtFieldActionPerformed

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyBtn;
    private javax.swing.JTextField labelTxtField;
    private javax.swing.JTextField uuidTextField;
    // End of variables declaration//GEN-END:variables
}
