/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.properties.panels;

import com.j3d.engine.react.actions.VoidAction;
import com.j3d.gen.properties.Property;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.stream.Collectors;

import static com.j3d.Static.getPropertiesPanel;
import static com.j3d.Static.sceneManager;
import static com.j3d.engine.SceneManager.history;

/**
 *
 * @author yetnt
 */
public class StringProperty extends javax.swing.JPanel implements PropertyPanel<String> {

    ArrayList<Property<String, ?>> properties;

    /**
     * Creates new form StringProperty
     */
    public StringProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields();
    }

    @Override
    public void setFields() {
        if (singleProperty()) {
            textField.setText(getSingleProperty().getValueSupplier().get());
            if (getSingleProperty().isConstant())
                textField.setEnabled(false);
        } else {
            textField.setText("(multiple)");
            if (
                    getProperties().stream()
                            .anyMatch(Property::isConstant)
            )
                textField.setEnabled(false);
        }
    }

    @Override
    public ArrayList<Property<String, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        textField.setText("jTextField1");
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        VoidAction setText = new VoidAction() {

            final LocalTime now = LocalTime.now();
            final String value = textField.getText();
            final ArrayList<String> oldValues = getProperties()
                    .stream()
                    .map(Property::getValueSupplier)
                    .map(Supplier::get)
                    .collect(Collectors.toCollection(ArrayList::new));

            @Override
            public Void run() {
                getProperties()
                        .forEach(p -> p.getNewValueConsumer().accept(value));
                getPropertiesPanel().repaint();
                return null;
            }

            @Override
            public void undo() {
                for (int i = 0; i < getProperties().size(); i++) {
                    Property<String, ?> property = getProperties().get(i);
                    String value = oldValues.get(i);
                    property.getNewValueConsumer().accept(value);
                }
                getPropertiesPanel().repaint();
            }

            @Override
            public boolean isReversible() {
                return true;
            }

            @Override
            public String getDescription() {
                return getActionDesc("String", value);
            }

            @Override
            public LocalTime getTime() {
                return now;
            }
        };
        setText.run();
        history.add(setText);
    }//GEN-LAST:event_textFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
