/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings.panels;

import static com.j3d.engine.react.events.EventEmitter.genericAttach;
import static com.j3d.engine.react.events.EventEmitter.genericBroadcast;
import static com.j3d.engine.react.events.EventEmitter.genericDetach;
import static com.j3d.engine.react.events.EventEmitter.genericDetachAll;
import com.j3d.engine.react.events.EventListener;
import com.j3d.engine.react.events.EventPayload;
import com.j3d.engine.react.events.EventType;
import com.j3d.engine.react.events.spec.SettingUpdatedPayload;
import com.j3d.settings.Setting;
import com.j3d.settings.types.BooleanSetting;

import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class BooleanValueSPanel extends javax.swing.JPanel implements SettingPanel {

    /**
     * Creates new form BooleanValueSPanel
     */
    public BooleanValueSPanel(BooleanSetting setting, boolean defaultValue) {
        initComponents();
        setting.attach(this);
        settingLabel2.setText(setting.getName());
        this.setToolTipText(setting.getDescription());
        jCheckBox3.setSelected(defaultValue);
        jCheckBox3.addChangeListener(
                e -> setting.setValueNoBroadcast(jCheckBox3.isSelected())
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingLabel2 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();

        settingLabel2.setText("SettingLabel (hover for desc)");

        jCheckBox3.setText("Enabled");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingLabel2)
                    .addComponent(jCheckBox3))
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel settingLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public <K> void onEvent(EventType event, EventPayload<K> properties) {
        if (event != EventType.SETTINGS_CODE_UPDATED) return;
        if (properties instanceof SettingUpdatedPayload<?> sp) {
            jCheckBox3.setSelected((Boolean) sp.getNewValue());
        }
    }
}
