/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings.panels;

import com.j3d.engine.react.events.EventPayload;
import com.j3d.engine.react.events.EventType;
import com.j3d.engine.react.events.spec.SettingUpdatedPayload;
import com.j3d.gen.settings.types.EnumSetting;
import com.j3d.ui.J3DTheme;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class ButtonGroupSPanel extends javax.swing.JPanel implements SettingPanel {

    private ArrayList<JRadioButton> buttons = new ArrayList<>();

    /**
     * Creates new form ButtonGroupSPanel
     */
    public <E extends Enum> ButtonGroupSPanel(EnumSetting<E> setting) {
        initComponents();
        setting.attach(this);
        settingLabel3.setText(setting.getName());
        this.setToolTipText(setting.getDescription());

        for (E e : setting.getValues()) {
            JRadioButton btn = new JRadioButton(e.name());
            btn.setBackground(J3DTheme.UI_SURFACE.color());
            btn.setForeground(J3DTheme.TEXT_PRIMARY.color());
            btn.setName(e.name());
            btn.setSelected(e.equals(setting.getValue()));
            btn.addActionListener(
                    a -> {
                        if (!btn.isSelected()) return;
                        setting.setValueNoBroadcast(e);
                    }
            );
            this.add(btn);
            buttonGroup1.add(btn);
            buttons.add(btn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radioPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        settingLabel3 = new javax.swing.JLabel();

        radioPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel1);

        radioPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setBackground(J3DTheme.UI_SURFACE.color());
        setLayout(new java.awt.GridLayout(0, 1, 0, 3));

        settingLabel3.setForeground(J3DTheme.TEXT_PRIMARY.color());
        settingLabel3.setText("SettingLabel (hover for desc)");
        settingLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(settingLabel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel radioPanel;
    private javax.swing.JLabel settingLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public <K> void onEvent(EventType event, EventPayload<K> properties) {
        if (event != EventType.SETTINGS_CODE_UPDATED) return;
        for (JRadioButton btn : buttons) {
            if (btn.getName().equals(((Enum<?>) ((SettingUpdatedPayload<?>) properties).getNewValue()).name())) {
                btn.setSelected(true);
                return;
            }
        }
    }
}
