/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings.panels;

import com.j3d.engine.react.events.EventPayload;
import com.j3d.engine.react.events.EventType;
import com.j3d.engine.react.events.payloads.SettingUpdatedPayload;
import com.j3d.gen.settings.Setting;
import com.j3d.gen.settings.types.DoubleSetting;
import com.j3d.gen.settings.types.IntSetting;
import com.j3d.ui.theme.J3DTheme;

import javax.swing.*;
import java.util.function.Function;

/**
 *
 * @author ACER
 */
public class NumberValueSPanel<T extends Number> extends AbstractPanel<Setting<T>, T> {

    private Function<T, Integer> toInt;
    private Function<Integer, T> toT;


    /**
     * Creates new form numberValueSPanel
     */
    public NumberValueSPanel(Setting<T> setting, T min, T max, T steps, Function<T, Integer> toInt, Function<Integer, T> toT) {
        super(setting);
        initComponents();
        this.toInt = toInt;
        this.toT = toT;
        settingLabel1.setText(setting.getName());
        this.setToolTipText(setting.getDescription());
        jSlider1.setMinimum(toInt.apply(min));
        jSlider1.setMaximum(toInt.apply(max));
        jSlider1.setValue(toInt.apply(setting.getValue()));
        jSlider1.setMajorTickSpacing(toInt.apply(steps));

        jSpinner1.setValue(setting.getValue());

        jSlider1.addChangeListener(
                e -> jSpinner1.setValue(
                        toT.apply(jSlider1.getValue())
                )
        );

        jSpinner1.addChangeListener(
                e -> {
                    if (setting instanceof DoubleSetting ds)
                        ds.setValueNoBroadcast((Double) jSpinner1.getValue());
                    else if (setting instanceof IntSetting is)
                        is.setValueNoBroadcast((Integer) jSpinner1.getValue());

                    jSlider1.setValue(
                            toInt.apply((T) jSpinner1.getValue())
                    );
                }
        );

        if (setting instanceof DoubleSetting ds) {
            jSpinner1.setModel(
                    new SpinnerNumberModel(
                            ds.getValue().doubleValue(), ds.getMin(), ds.getMax(), (double)steps
                    )
            );
        } else if (setting instanceof IntSetting is) {
            jSpinner1.setModel(
                    new SpinnerNumberModel(
                            is.getValue().intValue(), is.getMin(), is.getMax(), (int)steps
                    )
            );
        }
        resetButton.addActionListener(
                e -> {
                    jSpinner1.setValue(setting.getDefaultValue());
                    jSlider1.setValue(toInt.apply(setting.getDefaultValue()));
                    setting.setValueNoBroadcast(setting.getDefaultValue());
                }
        );

        J3DTheme.commitAsGenericLbl(settingLabel1, false);
        J3DTheme.commitAsGenericUi(this);
        J3DTheme.commitAsGenericUi(jSlider1);
        J3DTheme.commitAsGenericUi(jSpinner1);
        J3DTheme.commitAsGenericLbl(resetButton, true);
    }

    @Override
    public void calculate() {
        jSlider1.setValue(toInt.apply(setting.getValue()));
        jSpinner1.setValue(setting.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSpinner1 = new javax.swing.JSpinner();
        resetButton = new javax.swing.JButton();

        setBackground(J3DTheme.UI_SURFACE.color());

        settingLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        settingLabel1.setText("SettingLabel (hover for desc)");

        jSlider1.setBackground(J3DTheme.UI_SURFACE.color());
        jSlider1.setForeground(J3DTheme.TEXT_PRIMARY.color());

        jSpinner1.setOpaque(true);

        resetButton.setBackground(J3DTheme.BACKGROUND.color());
        resetButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        resetButton.setText("Reset Value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingLabel1)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel settingLabel1;
    // End of variables declaration//GEN-END:variables


    @Override
    public <K> void onEvent(EventType event, EventPayload<K> properties) {
        if (event != EventType.SETTING_CODE_UPDATED) return;
        if (properties instanceof SettingUpdatedPayload<?> sp) {
            //noinspection unchecked
            jSlider1.setValue(toInt.apply((T) sp.getNewValue()));
            jSpinner1.setValue(sp.getNewValue());
        }
    }

}
