/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings.panels;

import com.j3d.engine.react.events.EventPayload;
import com.j3d.engine.react.events.EventType;
import com.j3d.gen.settings.types.ComplexSetting;
import com.j3d.ui.theme.J3DTheme;
import com.j3d.utility.generic.func.TriFunction;

import java.awt.event.ActionEvent;
import java.util.function.BiFunction;
import javax.swing.JLabel;

/**
 *
 * @author ACER
 */
public class PopoutSPanel<T> extends AbstractPanel<ComplexSetting<T>, T> {

    TriFunction<ActionEvent, JLabel, PopoutSPanel<T>, T> onOpen;
    ComplexSetting<T> setting;

    /**
     * Creates new form PopoutSPanel
     */
    public PopoutSPanel(String initalValue, ComplexSetting<T> setting, TriFunction<ActionEvent, JLabel, PopoutSPanel<T>, T> onOpen) {
        super(setting);
        initComponents();
        valueLabel.setText(initalValue);
        settingLabel4.setText(setting.getName());
        this.setToolTipText(setting.getDescription());
        this.onOpen = onOpen;
        this.setting = setting;
        J3DTheme.commitAsGenericLbl(settingLabel4, false);
        J3DTheme.commitAsGenericUi(this);
        J3DTheme.commitAsGenericLbl(jButton1, true);
        J3DTheme.commitAsGenericLbl(valueLabel, true);
    }

    @Override
    public void calculate() {
        valueLabel.setText(setting.getValue().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();

        setBackground(J3DTheme.UI_SURFACE.color());

        settingLabel4.setForeground(J3DTheme.TEXT_PRIMARY.color());
        settingLabel4.setText("SettingLabel (hover for desc)");

        jButton1.setBackground(J3DTheme.BACKGROUND.color());
        jButton1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jButton1.setText("Set Value");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        valueLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        valueLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        valueLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingLabel4)
                    .addComponent(jButton1)
                    .addComponent(valueLabel))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setting.setValue(onOpen.apply(evt, valueLabel, this));
        valueLabel.setText(setting.getOnCreate().get());
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel settingLabel4;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public <K> void onEvent(EventType event, EventPayload<K> properties) {
        return;
    }
}
