package com.j3d.engine.geometry.geo3d;

import com.j3d.Static;
import com.j3d.engine.geometry.geo3d.matrix.Vector3;

import java.awt.*;
import java.util.ArrayList;
import java.util.function.Function;

import static com.j3d.Static.sceneManager;

public class Sampler {

    /**
     * Generates a list of points forming a regular N-gon (polygon) on a specified axisPlane.
     * The points are generated by rotating a vector around the axisPlane's normal, starting from a given centre.
     *
     * @param radius The radius of the N-gon (distance from the centre to each vertex).
     * @param axisPlane The axisPlane on which the N-gon lies. This axisPlane will be normalised internally.
     * @param n The number of sides (and vertices) of the N-gon.
     * @param mapper A function to transform each generated Vector3 point into an object of type T.
     * @param <T> The type of objects to be returned in the list.
     * @return An ArrayList of objects of type T, representing the vertices of the N-gon.
     */
    public static <T> ArrayList<T> ngon(double radius, AxisPlane axisPlane, int n, Function<Vector3, T> mapper) {
        ArrayList<T> objs = new ArrayList<>();
        axisPlane = axisPlane.normalize();
        Vector3 u = axisPlane.v1();
        Vector3 v = axisPlane.v2();

        // optional: orthogonalise v against u
//        v = v.sub(u.scale(v.dot(u))).normalize();

        for (int i = 0; i < n; i++) {
            double theta = 2 * Math.PI * i / n;
            Vector3 point = axisPlane.origin()
                    .add(u.scale(radius * Math.cos(theta)))
                    .add(v.scale(radius * Math.sin(theta)));
            objs.add(mapper.apply(point));
        }
        return objs;
    }

    /**
     * Generates a list of Vector3 points forming a regular N-gon (polygon) on a specified axisPlane.
     * This is an overloaded method that directly returns Vector3 objects.
     *
     * @param radius The radius of the N-gon (distance from the centre to each vertex).
     * @param axisPlane The axisPlane on which the N-gon lies. This axisPlane will be normalised internally.
     * @param n The number of sides (and vertices) of the N-gon.
     * @return An ArrayList of Vector3 objects, representing the vertices of the N-gon.
     */
    public static ArrayList<Vector3> ngon(double radius, AxisPlane axisPlane, int n) {
        ArrayList<Vector3> objs = new ArrayList<>();
        axisPlane = axisPlane.normalize();
        Vector3 u = axisPlane.v1();
        Vector3 v = axisPlane.v2();

        // optional: orthogonalise v against u
//        v = v.sub(u.scale(v.dot(u))).normalize();

        for (int i = 0; i < n; i++) {
            double theta = 2 * Math.PI * i / n;
            Vector3 point = axisPlane.origin()
                    .add(u.scale(radius * Math.cos(theta)))
                    .add(v.scale(radius * Math.sin(theta)));
            objs.add(point);
        }
        return objs;
    }

    public static void joinNGonArbitaryVectors(ArrayList<Vector3> vector3list, Graphics2D g) {
        for (int i = 0; i < vector3list.size(); i++) {
            Vector3 vector3 = vector3list.get(i);
            Vector3 nextVector3 = vector3list.get((i + 1) % vector3list.size());
            sceneManager.drawLine3D(
                    g, vector3, nextVector3, Static.camera
            );
        }
    }
}
