/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui;

/**
 *
 * @author ACER
 */
public class Toolbox extends javax.swing.JPanel {

    /**
     * Creates new form Toolbox
     */
    public Toolbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolboxScrollpane = new javax.swing.JScrollPane();
        toolboxInnerPanel = new javax.swing.JPanel();
        btnA_panel = new javax.swing.JPanel();
        btnA = new javax.swing.JButton();
        btnA_label = new javax.swing.JLabel();
        btnA_panel1 = new javax.swing.JPanel();
        btnA1 = new javax.swing.JButton();
        btnA_label1 = new javax.swing.JLabel();
        btnA_panel2 = new javax.swing.JPanel();
        btnA2 = new javax.swing.JButton();
        btnA_label2 = new javax.swing.JLabel();
        btnA_panel3 = new javax.swing.JPanel();
        btnA3 = new javax.swing.JButton();
        btnA_label3 = new javax.swing.JLabel();
        btnA_panel4 = new javax.swing.JPanel();
        btnA4 = new javax.swing.JButton();
        btnA_label4 = new javax.swing.JLabel();

        toolboxScrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        toolboxScrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        toolboxInnerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, -4));

        btnA_panel.setMaximumSize(new java.awt.Dimension(100, 120));
        btnA_panel.setMinimumSize(new java.awt.Dimension(120, 120));
        btnA_panel.setPreferredSize(new java.awt.Dimension(100, 120));
        btnA_panel.setLayout(new javax.swing.BoxLayout(btnA_panel, javax.swing.BoxLayout.Y_AXIS));

        btnA.setText("examplebtn");
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        btnA_panel.add(btnA);

        btnA_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA_label.setText("default label");
        btnA_label.setMaximumSize(new java.awt.Dimension(100, 16));
        btnA_label.setMinimumSize(new java.awt.Dimension(120, 16));
        btnA_label.setPreferredSize(new java.awt.Dimension(120, 16));
        btnA_panel.add(btnA_label);

        toolboxInnerPanel.add(btnA_panel);

        btnA_panel1.setMaximumSize(new java.awt.Dimension(100, 120));
        btnA_panel1.setMinimumSize(new java.awt.Dimension(120, 120));
        btnA_panel1.setPreferredSize(new java.awt.Dimension(100, 120));
        btnA_panel1.setLayout(new javax.swing.BoxLayout(btnA_panel1, javax.swing.BoxLayout.Y_AXIS));

        btnA1.setText("examplebtn");
        btnA1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA1.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA1.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA1.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });
        btnA_panel1.add(btnA1);

        btnA_label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA_label1.setText("default label");
        btnA_label1.setMaximumSize(new java.awt.Dimension(100, 16));
        btnA_label1.setMinimumSize(new java.awt.Dimension(120, 16));
        btnA_label1.setPreferredSize(new java.awt.Dimension(120, 16));
        btnA_panel1.add(btnA_label1);

        toolboxInnerPanel.add(btnA_panel1);

        btnA_panel2.setMaximumSize(new java.awt.Dimension(100, 120));
        btnA_panel2.setMinimumSize(new java.awt.Dimension(120, 120));
        btnA_panel2.setPreferredSize(new java.awt.Dimension(100, 120));
        btnA_panel2.setLayout(new javax.swing.BoxLayout(btnA_panel2, javax.swing.BoxLayout.Y_AXIS));

        btnA2.setText("examplebtn");
        btnA2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA2.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA2.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA2.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });
        btnA_panel2.add(btnA2);

        btnA_label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA_label2.setText("default label");
        btnA_label2.setMaximumSize(new java.awt.Dimension(100, 16));
        btnA_label2.setMinimumSize(new java.awt.Dimension(120, 16));
        btnA_label2.setPreferredSize(new java.awt.Dimension(120, 16));
        btnA_panel2.add(btnA_label2);

        toolboxInnerPanel.add(btnA_panel2);

        btnA_panel3.setMaximumSize(new java.awt.Dimension(100, 120));
        btnA_panel3.setMinimumSize(new java.awt.Dimension(120, 120));
        btnA_panel3.setPreferredSize(new java.awt.Dimension(100, 120));
        btnA_panel3.setLayout(new javax.swing.BoxLayout(btnA_panel3, javax.swing.BoxLayout.Y_AXIS));

        btnA3.setText("examplebtn");
        btnA3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA3.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA3.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA3.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA3ActionPerformed(evt);
            }
        });
        btnA_panel3.add(btnA3);

        btnA_label3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA_label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA_label3.setText("default label");
        btnA_label3.setMaximumSize(new java.awt.Dimension(100, 16));
        btnA_label3.setMinimumSize(new java.awt.Dimension(120, 16));
        btnA_label3.setPreferredSize(new java.awt.Dimension(120, 16));
        btnA_panel3.add(btnA_label3);

        toolboxInnerPanel.add(btnA_panel3);

        btnA_panel4.setMaximumSize(new java.awt.Dimension(100, 120));
        btnA_panel4.setMinimumSize(new java.awt.Dimension(120, 120));
        btnA_panel4.setPreferredSize(new java.awt.Dimension(100, 120));
        btnA_panel4.setLayout(new javax.swing.BoxLayout(btnA_panel4, javax.swing.BoxLayout.Y_AXIS));

        btnA4.setText("examplebtn");
        btnA4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA4.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA4.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA4.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA4ActionPerformed(evt);
            }
        });
        btnA_panel4.add(btnA4);

        btnA_label4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA_label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA_label4.setText("default label");
        btnA_label4.setMaximumSize(new java.awt.Dimension(100, 16));
        btnA_label4.setMinimumSize(new java.awt.Dimension(120, 16));
        btnA_label4.setPreferredSize(new java.awt.Dimension(120, 16));
        btnA_panel4.add(btnA_label4);

        toolboxInnerPanel.add(btnA_panel4);

        toolboxScrollpane.setViewportView(toolboxInnerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolboxScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolboxScrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JLabel btnA_label;
    private javax.swing.JLabel btnA_label1;
    private javax.swing.JLabel btnA_label2;
    private javax.swing.JLabel btnA_label3;
    private javax.swing.JLabel btnA_label4;
    private javax.swing.JPanel btnA_panel;
    private javax.swing.JPanel btnA_panel1;
    private javax.swing.JPanel btnA_panel2;
    private javax.swing.JPanel btnA_panel3;
    private javax.swing.JPanel btnA_panel4;
    private javax.swing.JPanel toolboxInnerPanel;
    private javax.swing.JScrollPane toolboxScrollpane;
    // End of variables declaration//GEN-END:variables
}
