<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.j3d</groupId>
    <artifactId>J3Engine</artifactId>
    <version>1.0.0</version>
    

    <dependencies>
        <!-- TO INSTALL THE BELOW DEPENDENCY (in netbeans):
                1. Right click the "jaiva-1.0.0.jar" file in the Dependencies folder of the project
                2. Click "Manually Install Artifact"
                3. Locate the jaiva.jar file within (this project directory)/lib/bin/jaiva.jar
                4. After install it should work fine.
                
                Before this worked with jsut systemPath (systemPath is deprecated i'm aware)
                on IntelliJ, however when i tried it on NetBeans it refused to work.
                This was the only work around to no local files and 
        -->
        <dependency>
            <groupId>jaiva</groupId>
            <artifactId>jaiva</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>