/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.settings.popouts;

import com.j3d.Static;
import com.j3d.settings.CoreSettings;
import com.j3d.settings.Settings;
import com.j3d.storage.db.DatabaseManager;
import com.j3d.storage.db.themes.Theme;
import com.j3d.ui.J3DTheme;

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;

/**
 *
 * @author ACER
 */
public class ThemeChanger extends javax.swing.JFrame {

    private HashMap<String, Color> themeOptionMap = new HashMap<>();
    private int selectedId = 1;
    private final ButtonGroup radioButtonGroup = new ButtonGroup();

    /**
     * Creates new form ThemeChanger
     */
    public ThemeChanger() {
        initComponents();
        for (Theme theme : DatabaseManager.tblThemes.themes) {
            radio(theme.themeName.getValue(), theme.themeId);
        }
        buttons.repaint();
        buttons.revalidate();
        this.revalidate();
        this.repaint();
    }

    private JRadioButton radio(String title, int id) {
        JRadioButton rd = new JRadioButton();

        if (J3DTheme.getCurrentLoadedThemeId() == id)
            rd.setSelected(true);

        rd.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
        rd.setForeground(J3DTheme.TEXT_PRIMARY.color());
        rd.setText(title);
        rd.addActionListener(e -> {
            themeOptionMap = DatabaseManager.tblThemes.themes.stream().filter(
                    t -> t.themeId == id
            ).findFirst().orElseGet(
                    () -> DatabaseManager.tblThemes.themes.getFirst()
            ).toColorHashMap();
            selectedId = id;
            setColors();
            drawPanel.repaint();
            this.repaint();
            this.revalidate();
        });

        radioButtonGroup.add(rd);
        buttons.add(rd);

        return rd;
    }

    private Color colorOf(J3DTheme theme) {
        return J3DTheme.colorFromMap(theme, themeOptionMap);
    }

    private void setColors() {
        drawPanel.setBackground(colorOf(J3DTheme.UI_SURFACE));
        jPanel2.setBackground(colorOf(J3DTheme.BACKGROUND));
        jLabel3.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        jButton2.setBackground(colorOf(J3DTheme.BACKGROUND));
        jButton2.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        jLabel2.setBackground(colorOf(J3DTheme.TEXT_PRIMARY));
        jLabel2.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        innerPanel.setBackground(colorOf(J3DTheme.BACKGROUND));
        jButton3.setBackground(colorOf(J3DTheme.UI_SURFACE));
        jButton3.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        drawPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        innerPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        enterThemeChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(J3DTheme.UI_SURFACE.color());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(J3DTheme.UI_SURFACE.color());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setText("Choose A Theme");

        buttons.setBackground(J3DTheme.UI_SURFACE.color());
        buttons.setMinimumSize(new java.awt.Dimension(229, 100));
        buttons.setLayout(new java.awt.GridLayout(0, 1));

        drawPanel.setBackground(colorOf(J3DTheme.UI_SURFACE));
        drawPanel.setMaximumSize(new java.awt.Dimension(264, 333));
        drawPanel.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(colorOf(J3DTheme.BACKGROUND));
        jPanel2.setMaximumSize(new java.awt.Dimension(264, 166));
        jPanel2.setMinimumSize(new java.awt.Dimension(264, 166));
        jPanel2.setPreferredSize(new java.awt.Dimension(264, 166));

        jLabel3.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BACKGROUND COLOUR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        drawPanel.add(jPanel2, gridBagConstraints);

        jPanel4.setMaximumSize(new java.awt.Dimension(264, 166));
        jPanel4.setMinimumSize(new java.awt.Dimension(264, 166));
        jPanel4.setOpaque(false);

        jButton2.setBackground(colorOf(J3DTheme.BACKGROUND));
        jButton2.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        jButton2.setText("a button");

        jLabel2.setBackground(colorOf(J3DTheme.TEXT_PRIMARY));
        jLabel2.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        jLabel2.setText("UI Element");

        innerPanel.setBackground(colorOf(J3DTheme.BACKGROUND));

        jButton3.setBackground(colorOf(J3DTheme.UI_SURFACE));
        jButton3.setForeground(colorOf(J3DTheme.TEXT_PRIMARY));
        jButton3.setText("some other button");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout innerPanelLayout = new javax.swing.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(innerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        drawPanel.add(jPanel4, gridBagConstraints);

        enterThemeChange.setText("Change Theme");
        enterThemeChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterThemeChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(enterThemeChange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(enterThemeChange)
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterThemeChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterThemeChangeActionPerformed
        // TODO: Somehow change entire app theme or ask user to close and open for theme change.
        CoreSettings.user.themeId.setValue(
                selectedId
        );
        CoreSettings.user.save();

        Static.settings.panel().dispose();

        Static.mainFrame.repaint();
        Static.mainFrame.revalidate();

        this.dispose();
        Settings.themeChanger = null;
    }//GEN-LAST:event_enterThemeChangeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemeChanger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JButton enterThemeChange;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
