/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings.popouts;

import com.j3d.ui.theme.J3DTheme;
import com.j3d.ui.theme.ThemeEntry;
import com.j3d.ui.theme.ThemeKey;
import com.j3d.utility.generators.JLabelRichText;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.function.Consumer;
import java.util.function.Function;

/**
 *
 * @author yetnt
 */
public class ThemePropertyPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThemePropertyPanel
     */
    public ThemePropertyPanel(ButtonGroup gp, ThemeEntry from, ThemeKey key, Function<ActionEvent, Color> actionEventConsumer) {
        initComponents();
        gp.add(themeRadioBtn);
        themeColourLabel.setText(
                new JLabelRichText("~~~~~~~")
                        .font(J3DTheme.TEXT_PRIMARY.color(), "4", from.getEntries().get(key))
                        .wrapHTML()
        );

        themeRadioBtn.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
        themeRadioBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());

        themeColourLabel.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
        themeColourLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());

        this.setBackground(J3DTheme.UI_SURFACE.color());

        themeRadioBtn.setText(key.toString());
        themeRadioBtn.addActionListener(e -> {
            themeColourLabel.setText(
                    new JLabelRichText("~~~~~~~")
                            .font(J3DTheme.TEXT_PRIMARY.color(), "4", actionEventConsumer.apply(e))
                            .wrapHTML()
            );
            this.revalidate();
            this.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themeRadioBtn = new javax.swing.JRadioButton();
        themeColourLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(206, 35));
        setMinimumSize(new java.awt.Dimension(206, 35));

        themeRadioBtn.setText("jRadioButton1");

        themeColourLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(themeColourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themeRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themeRadioBtn)
                    .addComponent(themeColourLabel))
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel themeColourLabel;
    private javax.swing.JRadioButton themeRadioBtn;
    // End of variables declaration//GEN-END:variables
}
