/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.tb;

import com.j3d.Static;
import com.j3d.ui.CursorManager;
import com.j3d.ui.CursorNames;
import com.j3d.ui.J3DTheme;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;
import java.util.function.Consumer;

/**
 *
 * @author ACER
 */
public class Subbox extends javax.swing.JPanel {

    public Point mousePos;

    /**
     * Creates new form Toolbox
     */
    public Subbox() {
        initComponents();
    }

    public Subbox(Consumer<Subbox> init) {
        initComponents();
        init.accept(this);
    }

    public Subbox add(String label, ActionListener actionListener, String imageFileName) {
        JButton l = add(label, actionListener);
        ImageIcon unscaled = new ImageIcon(Objects.requireNonNull(ToolboxButtons.class.getResource("/art/toolbox/" + imageFileName)));
        Image scaled = unscaled.getImage().getScaledInstance(l.getPreferredSize().width, l.getPreferredSize().height, Image.SCALE_SMOOTH);
        l.setText(""); // Set the text to nun so that it doesnt push the picture
        l.setIcon(new ImageIcon(scaled));
        return this;
    }

    public JButton add(String label, ActionListener actionListener) {
        JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setMaximumSize(new java.awt.Dimension(100, 120));
        buttonPanel.setMinimumSize(new java.awt.Dimension(120, 120));
        buttonPanel.setPreferredSize(new java.awt.Dimension(100, 120));
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));
        buttonPanel.setBackground(J3DTheme.UI_SURFACE.color());

        JButton btnA = new javax.swing.JButton();
        btnA.setText("examplebtn");
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA.addActionListener(actionListener);
        btnA.setBackground(J3DTheme.BACKGROUND.color());
        btnA.setForeground(J3DTheme.TEXT_PRIMARY.color());
        btnA.setCursor(CursorManager.get(CursorNames.HAND_POINTER));
        buttonPanel.add(btnA);

        JLabel label1 = new javax.swing.JLabel();
        label1.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText(label);
        label1.setMaximumSize(new java.awt.Dimension(100, 16));
        label1.setMinimumSize(new java.awt.Dimension(120, 16));
        label1.setPreferredSize(new java.awt.Dimension(120, 16));
        label1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        buttonPanel.add(label1);

        toolboxInnerPanel.add(buttonPanel);
        return btnA;
    }

    public void delete() {
        this.setVisible(false);
        this.setEnabled(false);
        Static.mainFrame.getLayeredPane().remove(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolboxScrollpane = new javax.swing.JScrollPane();
        toolboxInnerPanel = new javax.swing.JPanel();
        btnA_panel = new javax.swing.JPanel();
        btnA = new javax.swing.JButton();
        btnA_label = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 32767));
        setPreferredSize(new java.awt.Dimension(1000, 134));

        toolboxScrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        toolboxScrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        toolboxInnerPanel.setBackground(J3DTheme.UI_SURFACE.color());
        toolboxInnerPanel.setMinimumSize(new java.awt.Dimension(100, 112));
        toolboxInnerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, -4));

        btnA_panel.setBackground(J3DTheme.UI_SURFACE.color());
        btnA_panel.setMaximumSize(new java.awt.Dimension(100, 120));
        btnA_panel.setMinimumSize(new java.awt.Dimension(120, 120));
        btnA_panel.setPreferredSize(new java.awt.Dimension(100, 120));
        btnA_panel.setLayout(new javax.swing.BoxLayout(btnA_panel, javax.swing.BoxLayout.Y_AXIS));

        btnA.setBackground(J3DTheme.BACKGROUND.color());
        btnA.setForeground(J3DTheme.TEXT_PRIMARY.color());
        btnA.setText("examplebtn");
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA.setMaximumSize(new java.awt.Dimension(100, 100));
        btnA.setMinimumSize(new java.awt.Dimension(100, 100));
        btnA.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        btnA_panel.add(btnA);

        btnA_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA_label.setForeground(J3DTheme.TEXT_PRIMARY.color());
        btnA_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA_label.setText("default label");
        btnA_label.setMaximumSize(new java.awt.Dimension(100, 16));
        btnA_label.setMinimumSize(new java.awt.Dimension(120, 16));
        btnA_label.setPreferredSize(new java.awt.Dimension(120, 16));
        btnA_panel.add(btnA_label);

        toolboxInnerPanel.add(btnA_panel);

        ToolboxButtons.getToolboxButtons().forEach(
            toolboxInnerPanel::add
        );

        toolboxScrollpane.setViewportView(toolboxInnerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolboxScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolboxScrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JLabel btnA_label;
    private javax.swing.JPanel btnA_panel;
    public javax.swing.JPanel toolboxInnerPanel;
    public javax.swing.JScrollPane toolboxScrollpane;
    // End of variables declaration//GEN-END:variables
}
