/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.settings;

import com.j3d.StaticRefs;
import com.j3d.gen.settings.Settings;
import com.j3d.ui.dialog.AreYouSure;
import com.j3d.ui.theme.swing.J3DScrollBarUI;
import com.j3d.ui.theme.J3DTheme;

import javax.swing.*;

/**
 *
 * @author ACER
 */
public class PreferencesFrame extends javax.swing.JFrame {

    /**
     * Creates new form PreferencesFrame
     */
    public PreferencesFrame() {
        initComponents();
        saveBtn.setVisible(false);
        StaticRefs.getSettings().getAllChildren().forEach(child -> {
            System.out.println("Adding + " + child);
            jPanel1.add(child.panel());
            System.out.println("Added");
        });
        J3DScrollBarUI.setBars(jScrollPane1);
        this.pack();
        this.repaint();
        this.revalidate();
        StaticRefs.getLog().uiPrintLn("PreferencesFrame completed building");

        J3DTheme.commitAsGenericUi(this);
        J3DTheme.commitAsGenericLbl(jLabel1, false);
        J3DTheme.commitAsGenericUi(jPanel1);
        J3DTheme.commitAsGenericUi(jScrollPane1);
        J3DTheme.commitAsGenericUi(preferencesPanel);
        J3DTheme.commitAsGenericLbl(saveBtn, true);
        J3DTheme.commitAsGenericLbl(defualtBtn, true);

        JFrame t = this;

        // when window closing
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (!Settings.isPreferencesSaved()) {
                    AreYouSure ays = new AreYouSure(
                            t, true, "You have unsaved preferences!"
                    );
                    ays.setVisible(true);
                    if (ays.canProceed()) {
                        // continue normal close operation
                        super.windowClosing(windowEvent);
                    }
                }
            }
        });
    }

    public void onChange() {
        jLabel1.setText("Preferences*");
        saveBtn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preferencesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        defualtBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setTitle("J3D Settings Mfwethu");
        setBackground(J3DTheme.UI_SURFACE.color());
        setIconImage(StaticRefs.logo());
        setMinimumSize(new java.awt.Dimension(300, 0));

        preferencesPanel.setBackground(J3DTheme.UI_SURFACE.color());
        preferencesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        jLabel1.setBackground(J3DTheme.UI_SURFACE.color());
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preferences");
        jLabel1.setOpaque(true);
        preferencesPanel.add(jLabel1);

        saveBtn.setBackground(J3DTheme.BACKGROUND.color());
        saveBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(75, 40));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        preferencesPanel.add(saveBtn);

        defualtBtn.setBackground(J3DTheme.BACKGROUND.color());
        defualtBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        defualtBtn.setText("Default");
        defualtBtn.setPreferredSize(new java.awt.Dimension(75, 40));
        defualtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defualtBtnActionPerformed(evt);
            }
        });
        preferencesPanel.add(defualtBtn);

        getContentPane().add(preferencesPanel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(J3DTheme.UI_SURFACE.color());
        jScrollPane1.setForeground(J3DTheme.UI_SURFACE.color());
        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(J3DTheme.UI_SURFACE.color());
        jPanel1.setForeground(J3DTheme.UI_SURFACE.color());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        StaticRefs.getSettings().write();
        saveBtn.setVisible(false);
        jLabel1.setText("Preferences");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void defualtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defualtBtnActionPerformed
        PreferencesFrame t = this;
        AreYouSure ays = new AreYouSure(
                t, true, "This will reset all the preferences to engine defaults."
        );
        ays.setVisible(true);
        if (ays.canProceed())
            StaticRefs.getSettings().toDefault();

    }//GEN-LAST:event_defualtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreferencesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton defualtBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel preferencesPanel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
