/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings;

import com.j3d.settings.SettingsChild;
import com.j3d.settings.SettingsParent;
import com.j3d.ui.J3DTheme;

import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class SettingsParentPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsParentPanel
     */
    public SettingsParentPanel(SettingsParent sp) {
        initComponents();
        settingsTitleLabel.setText(sp.getName());
        settingsDescriptionLabel.setText(sp.getDescription());

    }

    public SettingsParentPanel addChildren(ArrayList<SettingsChild> settings) {
        for (SettingsChild setting : settings) {
            innerSettingsPanel.add(setting.panel());
        }
        this.repaint();
        this.revalidate();
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsTitleLabel = new javax.swing.JLabel();
        settingsDescriptionLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        innerSettingsPanel = new javax.swing.JPanel();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMinimumSize(new java.awt.Dimension(733, 72));

        settingsTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        settingsTitleLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        settingsTitleLabel.setText("SettingsTitle");

        settingsDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        settingsDescriptionLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        settingsDescriptionLabel.setText("Settings Description");

        innerSettingsPanel.setMaximumSize(new java.awt.Dimension(32771823, 32771823));
        innerSettingsPanel.setLayout(new javax.swing.BoxLayout(innerSettingsPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(settingsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(settingsDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(innerSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(innerSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerSettingsPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel settingsDescriptionLabel;
    private javax.swing.JLabel settingsTitleLabel;
    // End of variables declaration//GEN-END:variables
}
