/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.settings;

import com.j3d.settings.SettingsChild;
import com.j3d.settings.SettingsParent;
import com.j3d.ui.J3DTheme;

import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class SettingsParentPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsParentPanel
     */
    public SettingsParentPanel(SettingsParent sp) {
        initComponents();
        settingsTitleLabel.setText(sp.getName());
        settingsDescriptionLabel.setText(sp.getDescription());

    }

    public SettingsParentPanel addChildren(ArrayList<SettingsChild> settings) {
        for (SettingsChild setting : settings) {
            innerSettingsPanel.add(setting.panel());
        }
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsTitleLabel = new javax.swing.JLabel();
        settingsDescriptionLabel = new javax.swing.JLabel();
        settingsScrollPane = new javax.swing.JScrollPane();
        innerSettingsPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        settingsTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        settingsTitleLabel.setForeground(J3DTheme.ASH_GREY.color());
        settingsTitleLabel.setText("SettingsTitle");

        settingsDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        settingsDescriptionLabel.setForeground(J3DTheme.ASH_GREY.color());
        settingsDescriptionLabel.setText("Settings Description");

        innerSettingsPanel.setLayout(new java.awt.GridLayout(0, 1));
        settingsScrollPane.setViewportView(innerSettingsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(settingsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(settingsDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsScrollPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerSettingsPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel settingsDescriptionLabel;
    private javax.swing.JScrollPane settingsScrollPane;
    private javax.swing.JLabel settingsTitleLabel;
    // End of variables declaration//GEN-END:variables
}
