/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine;

import com.j3d.Static;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.function.Consumer;

/**
 *
 * @author ACER
 */
public class FloatingPanel extends javax.swing.JPanel {

    private JFrame frame = null;
    private String name;
    private boolean isPopped = false;
    private boolean isHidden = false;
    private boolean moving = false;
    private MouseMotionListener msl;
    private Point lastLocation = new Point(120, 240);

    /**
     * Creates new form FloatingPanel
     */
    public FloatingPanel(String name, Component c, Consumer<Component> consumer) {
        this.name = name;
        initComponents();
        c.setBounds(0, 0, c.getPreferredSize().width, c.getPreferredSize().height);
        consumer.accept(c);
        addComponentToPanel(c);
        this.revalidate();
        EngineFrame.addFloater(this);
        this.setVisible(true);
        JPanel panel = this;
        msl = new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                Point newP = new Point(e.getX() - panel.getSize().width + 5, e.getY() - 35);
                panel.setLocation(newP);
                Static.mainFrame.repaint();
                lastLocation = newP;
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                Point newP = new Point(e.getX() - panel.getSize().width + 5, e.getY() - 35);
                panel.setLocation(newP);
                Static.mainFrame.repaint();
                lastLocation = newP;
            }
        };
    }

    public JFrame popOut() {
        if (frame == null && !isPopped) {
            isPopped = true;
            isHidden = false;
            frame = new JFrame(name);
            frame.setMinimumSize(this.getMinimumSize());
            frame.setMaximumSize(this.getMaximumSize());
            frame.setPreferredSize(this.getPreferredSize());
            frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            stickButton.setVisible(false);
            EngineFrame.removeFloater(this);
            Static.mainFrame.revalidate();
            frame.add(this);
            frame.pack();
            frame.setLocationRelativeTo(Static.mainFrame);
            this.revalidate();
            frame.setVisible(true);
        }
        return frame;
    }

    public void popIn() {
        if (frame != null && isPopped) {
            isPopped = false;
            frame.setVisible(false);
            frame.dispose();
            frame = null;
            stickButton.setVisible(true);
            EngineFrame.addFloaterAt(this, lastLocation);
            EngineFrame.bringForward(this);
            this.setVisible(true);
            Static.mainFrame.revalidate();
        }
    }

    public boolean isHidden() {
        return isHidden;
    }

    public boolean isPopped() {
        return isPopped;
    }

    public void showThis() {
        if (isPopped)frame.setVisible(true);
        else this.setVisible(true);
        isHidden = false;
    }

    public void hideThis() {
        if (isPopped) frame.setVisible(false);
        else {
            if (moving) {
                Static.hoverLabel.error("  Finish moving the panel first.");
                return;
            }
            this.setVisible(false);
        }
        isHidden = true;
    }

    public void addComponentToPanel(Component c) {
        propertiesPanel.add(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsPanel = new javax.swing.JPanel();
        popButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        stickButton = new javax.swing.JButton();
        propertiesPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(862, 580));
        setLayout(new java.awt.BorderLayout());

        btnsPanel.setMaximumSize(new java.awt.Dimension(350, 23));
        btnsPanel.setLayout(new javax.swing.BoxLayout(btnsPanel, javax.swing.BoxLayout.LINE_AXIS));

        popButton.setText("pop");
        popButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popButtonActionPerformed(evt);
            }
        });
        btnsPanel.add(popButton);
        btnsPanel.add(jSeparator1);

        stickButton.setText("stick");
        stickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stickButtonActionPerformed(evt);
            }
        });
        btnsPanel.add(stickButton);

        add(btnsPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        add(propertiesPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void stickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stickButtonActionPerformed
        if (!isPopped) {
            if (moving) {
                Static.mainFrame.removeMouseMotionListener(msl);
                moving = false;
                this.setLocation(lastLocation);
            }
            else {
                Static.mainFrame.addMouseMotionListener(msl);
                moving = true;
            }
        }
        Static.hoverLabel.clear();
    }//GEN-LAST:event_stickButtonActionPerformed

    private void popButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popButtonActionPerformed
        if (isPopped) popIn();
        else popOut();
    }//GEN-LAST:event_popButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnsPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton popButton;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JButton stickButton;
    // End of variables declaration//GEN-END:variables
}
