/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine;

import com.j3d.StaticRefs;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.function.Consumer;

/**
 *
 * @author ACER
 */
public class FloatingPanel extends javax.swing.JPanel {

    private JFrame frame = null;
    private String name;
    private boolean isDocked = false;
    private boolean isHidden = true;
    private boolean moving = false;
    private MouseMotionListener msl;
    private Point lastLocation = new Point(120, 240);

    public FloatingPanel(String name) {
        this.name = name;
        initComponents();
        this.jLabel1.setText(name);
    }

    public void addComponentToPanel(Component c) {
        propertiesPanel.setLayout(new BorderLayout());
        propertiesPanel.add(c, BorderLayout.CENTER);
        this.setBounds(0, 0, c.getPreferredSize().width, c.getPreferredSize().height);
        propertiesPanel.setBounds(0, 0, c.getPreferredSize().width, c.getPreferredSize().height);
        c.setBounds(0, 0, c.getPreferredSize().width, c.getPreferredSize().height);
        c.setVisible(true);
        this.revalidate();
        this.repaint();
    }

    public void finish(Component c, Consumer<Component> consumer) {
        consumer.accept(c);
        addComponentToPanel(c);
//        c.revalidate();
//        c.repaint();
        JPanel panel = this;
        msl = new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // not required.
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                Point newP = new Point(e.getX() - panel.getSize().width + 5, e.getY() - 35);
                panel.setLocation(newP);
                StaticRefs.getMainFrame().repaint();
                lastLocation = newP;
            }
        };
        EngineFrame.addFloaterAt(this, lastLocation);
    }

    /**
     * Creates new form FloatingPanel
     */
    public FloatingPanel(String name, Component c, Consumer<Component> consumer) {
        this.name = name;
        initComponents();
        finish(c, consumer);
    }

    public JFrame dock() {
        if (frame == null && !isDocked) {
            isDocked = true;
            isHidden = false;
            frame = new JFrame(name);
            frame.setMinimumSize(this.getMinimumSize());
            frame.setMaximumSize(this.getMaximumSize());
            frame.setPreferredSize(this.getPreferredSize());
            frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            attachButton.setVisible(false);
            EngineFrame.removeFloater(this);
            StaticRefs.getMainFrame().revalidate();
            frame.add(this);
            frame.pack();
            frame.setLocationRelativeTo(StaticRefs.getMainFrame());
            this.revalidate();
            frame.setVisible(true);
        }
        return frame;
    }

    public void returnToFrame() {
        if (frame != null && isDocked) {
            isDocked = false;
            frame.setVisible(false);
            frame.dispose();
            frame = null;
            attachButton.setVisible(true);
            EngineFrame.addFloaterAt(this, lastLocation);
            EngineFrame.bringForward(this);
            this.setVisible(true);
            StaticRefs.getMainFrame().revalidate();
        }
    }

    public boolean isHidden() {
        return isHidden;
    }

    public boolean isDocked() {
        return isDocked;
    }

    public void showThis() {
        if (isDocked)frame.setVisible(true);
        else this.setVisible(true);
        isHidden = false;
    }

    public void hideThis() {
        if (isDocked) frame.setVisible(false);
        else {
            if (moving) {
                StaticRefs.getHoverLabel().error("  Finish moving the panel first.");
                return;
            }
            this.setVisible(false);
        }
        isHidden = true;
    }

    public void toggleHidden() {
        if (isHidden) showThis();
        else hideThis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsPanel = new javax.swing.JPanel();
        dockButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        attachButton = new javax.swing.JButton();
        propertiesPanel = new javax.swing.JPanel();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(862, 580));
        setLayout(new java.awt.BorderLayout());

        btnsPanel.setBackground(J3DTheme.UI_SURFACE.color());
        btnsPanel.setMaximumSize(new java.awt.Dimension(350, 23));
        btnsPanel.setLayout(new javax.swing.BoxLayout(btnsPanel, javax.swing.BoxLayout.LINE_AXIS));

        dockButton.setBackground(J3DTheme.BACKGROUND.color());
        dockButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        dockButton.setText("dock");
        dockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dockButtonActionPerformed(evt);
            }
        });
        btnsPanel.add(dockButton);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(3278, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 16));
        btnsPanel.add(jLabel1);

        attachButton.setBackground(J3DTheme.BACKGROUND.color());
        attachButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        attachButton.setText("attach");
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        btnsPanel.add(attachButton);

        add(btnsPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        add(propertiesPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        if (!isDocked) {
            if (!moving) {
                StaticRefs.getMainFrame().addMouseMotionListener(msl);
                moving = true;
                attachButton.setText("(detach)");
            } else {
                StaticRefs.getMainFrame().removeMouseMotionListener(msl);
                moving = false;
                this.setLocation(lastLocation);
                attachButton.setText("attach");
            }
        }
        StaticRefs.getHoverLabel().clear();
    }//GEN-LAST:event_attachButtonActionPerformed

    private void dockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dockButtonActionPerformed
        if (isDocked) returnToFrame();
        else dock();
    }//GEN-LAST:event_dockButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachButton;
    private javax.swing.JPanel btnsPanel;
    private javax.swing.JButton dockButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel propertiesPanel;
    // End of variables declaration//GEN-END:variables
}
