/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine;

import com.j3d.Static;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ACER
 */
public class FloatingPanel extends javax.swing.JPanel {

    private JFrame frame = null;
    private String name;
    private boolean isPopped = false;
    private boolean isHidden = false;

    /**
     * Creates new form FloatingPanel
     */
    public FloatingPanel(String name, Component c) {
        this.name = name;
        initComponents();
        addComponentToPanel(c);
        EngineFrame.addFloater(this);
        this.setVisible(true);
    }

    public JFrame popOut() {
        if (frame == null && !isPopped) {
            isPopped = true;
            isHidden = false;
            frame = new JFrame(name);
            frame.setMinimumSize(this.getMinimumSize());
            frame.setMaximumSize(this.getMaximumSize());
            frame.setPreferredSize(this.getPreferredSize());
            frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            frame.setUndecorated(true);
            EngineFrame.removeFloater(this);
            Static.mainFrame.revalidate();
            frame.add(this);
            frame.pack();
            frame.setLocationRelativeTo(Static.mainFrame);
            this.revalidate();
            frame.setVisible(true);
        }
        return frame;
    }

    public void popIn() {
        if (frame != null && isPopped) {
            isPopped = false;
            frame.setVisible(false);
            frame.dispose();
            frame = null;
            EngineFrame.addFloater(this);
            EngineFrame.bringForward(this);
            this.setVisible(isHidden);
            Static.mainFrame.revalidate();
        }
    }

    public boolean isHidden() {
        return isHidden;
    }

    public boolean isPopped() {
        return isPopped;
    }

    public void showThis() {
        if (isPopped)frame.setVisible(true);
        else this.setVisible(true);
        isHidden = false;
    }

    public void hideThis() {
        if (isPopped) frame.setVisible(false);
        else this.setVisible(false);
        isHidden = true;
    }

    public void addComponentToPanel(Component c) {
        propertiesPanel.add(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsPanel = new javax.swing.JPanel();
        popButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        closeButton = new javax.swing.JButton();
        propertiesPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(862, 580));
        setLayout(new java.awt.BorderLayout());

        btnsPanel.setMaximumSize(new java.awt.Dimension(350, 23));
        btnsPanel.setLayout(new javax.swing.BoxLayout(btnsPanel, javax.swing.BoxLayout.LINE_AXIS));

        popButton.setText("pop");
        popButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popButtonActionPerformed(evt);
            }
        });
        btnsPanel.add(popButton);
        btnsPanel.add(jSeparator1);

        closeButton.setText("close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        btnsPanel.add(closeButton);

        add(btnsPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        add(propertiesPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        if (isPopped) {
            frame.setVisible(false);
        } else {
            this.setVisible(false);
        }
        isHidden = true;
    }//GEN-LAST:event_closeButtonActionPerformed

    private void popButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popButtonActionPerformed
        if (isPopped) popIn();
        else popOut();
    }//GEN-LAST:event_popButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton popButton;
    private javax.swing.JPanel propertiesPanel;
    // End of variables declaration//GEN-END:variables
}
