/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.toolbox;

import com.j3d.ui.theme.swing.J3DScrollBarUI;
import com.j3d.ui.theme.J3DTheme;

/**
 *
 * @author ACER
 */
public class Toolbox extends javax.swing.JPanel {

    /**
     * Creates new form Toolbox
     */
    public Toolbox() {
        initComponents();
        J3DScrollBarUI.setBars(toolboxScrollpane);
        repaint();
        revalidate();
        J3DTheme.commitAsGenericUi(
                this
        );
        J3DTheme.commitAsGenericUi(toolboxScrollpane);
        J3DTheme.commitAsGenericUi(toolboxInnerPanel);
//        J3DTheme.commitAsGenericUi(btnA_panel);
//        J3DTheme.commitAsGenericUi(btnA);
//        J3DTheme.commitAsGenericLbl(btnA_label, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolboxScrollpane = new javax.swing.JScrollPane();
        toolboxInnerPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1000, 32767));
        setPreferredSize(new java.awt.Dimension(1000, 134));

        toolboxScrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        toolboxScrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        toolboxInnerPanel.setBackground(J3DTheme.UI_SURFACE.color());
        toolboxInnerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, -4));

        ToolboxButtons.getToolboxButtons().forEach(
            toolboxInnerPanel::add
        );

        toolboxScrollpane.setViewportView(toolboxInnerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolboxScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolboxScrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel toolboxInnerPanel;
    public javax.swing.JScrollPane toolboxScrollpane;
    // End of variables declaration//GEN-END:variables
}
