/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.docs;

import com.j3d.gen.docs.Documentation;
import com.j3d.gen.docs.reader.tokens.TLink;
import com.j3d.ui.theme.J3DTheme;

import java.util.ArrayList;

/**
 *
 * @author yetnt
 */
public class LinksPanel extends javax.swing.JPanel {

    /**
     * Creates new form TextPanel
     */
    public LinksPanel(DocsFrame parent, ArrayList<TLink> links, int width, Documentation doc) {
        initComponents();
        int totalHeight = 0;
        for (int i = 0; i < links.size(); i++) {
            LinkPanel lp = new LinkPanel(parent, i + 1, links.get(i), width, doc);
            add(lp);
            totalHeight += lp.getPreferredSize().height;
        }
        setMaximumSize(new java.awt.Dimension(getMaximumSize().width, totalHeight));

        J3DTheme.commitAsGenericUi(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(J3DTheme.UI_SURFACE.color());
        setForeground(J3DTheme.TEXT_PRIMARY.color());
        setMaximumSize(new java.awt.Dimension(558, 294));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
