/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.docs;

import com.j3d.StaticRefs;
import com.j3d.gen.docs.reader.DocsGenException;
import com.j3d.gen.docs.reader.tokens.TLink;
import com.j3d.ui.generic.J3DTheme;
import com.j3d.utility.Parsing;
import com.j3d.utility.generators.JLabelRichText;
import com.j3d.utility.generic.Pair;

import java.awt.*;
import java.io.File;
import java.util.ArrayList;

/**
 *
 * @author yetnt
 */
public class LinkPanel extends javax.swing.JPanel {

    private final TLink link;
    private final DocsFrame parentFrame;
    private final boolean isMainHelp;
    private final String id;

    public LinkPanel(DocsFrame parent, int refNum, TLink link, int length) {
        initComponents();
        parentFrame = parent;
        Dimension dim = new Dimension(length, getMaximumSize().height);
        setMaximumSize(dim);
        setMinimumSize(dim);
        setPreferredSize(dim);
        this.link = link;
        jLabel1.setText("[" + refNum + "] " + link.getContent());
        isMainHelp = false;
        id = "";
    }

    public LinkPanel(String id, Pair<String, File> pair, int width) {
        initComponents();

        String name = pair.first;

        jButton1.setText("Open");

        Dimension dim0 = new Dimension(
                100,
                30
        );
        jButton1.setMaximumSize(dim0);
        jButton1.setMinimumSize(dim0);
        jButton1.setPreferredSize(dim0);


        jLabel1.setText(
                new JLabelRichText(
                        name
                )
                        .heading(JLabelRichText.Heading.H1)
//                        .font("5")
                        .bold().italic().wrapHTML()
        );
        // set label height.
        Dimension dim1 = new Dimension(
                300,
                30);
        jLabel1.setMaximumSize(dim1);
        jLabel1.setMinimumSize(dim1);
        jLabel1.setPreferredSize(dim1);

        Dimension dim2 = new Dimension(width, 100);
        setMaximumSize(dim2);
        setMinimumSize(dim2);
        setPreferredSize(dim2);

        link = null;
        parentFrame = null;
        isMainHelp = true;
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(463, 20));
        setMinimumSize(new java.awt.Dimension(463, 20));
        setPreferredSize(new java.awt.Dimension(463, 20));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setLabelFor(jButton1);
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 16));
        add(jLabel1, new java.awt.GridBagConstraints());

        jButton1.setBackground(J3DTheme.BACKGROUND.color());
        jButton1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jButton1.setText("Go");
        jButton1.setMaximumSize(new java.awt.Dimension(60, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (isMainHelp) {
            StaticRefs.getDocsProvider().provideDocFrame(id).setVisible(true);
            return;
        }

        String url = link.getUrl();
        if (url.startsWith("http")) {
            // go to
            try {
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            } catch (java.io.IOException e1) {
                e1.printStackTrace();
            }
        } else {
            // something in ther app itself. TODO: handle later
            if (url.startsWith("#")) {
                // within the document.
                String header = url.substring(1).trim();

                parentFrame.scrollToHeader(header);
            } else if (url.contains("#")) {
                // link to other file, to a header.
                // split
                ArrayList<String> toks = Parsing.split(url, '#');
                if (toks.size() != 2) {
                    StaticRefs.getErrs().handle(
                            new DocsGenException(
                                    "Invalid link format: " + url
                            )
                    );
                }
                String otherFile = toks.getFirst();
                String header = toks.getLast();

                if (!otherFile.contains(".j3.md")) {
                    StaticRefs.getErrs().handle(
                            new DocsGenException(
                                    "Attempt to link to anon j3md file " + otherFile
                            ));
                }

                // remove .j3.md extension
                otherFile = otherFile.substring(0, otherFile.length() - 6);
                StaticRefs.getDocsProvider()
                        .provideDocFrame(otherFile) // get the other file
                        .scrollToHeader(header) // scroll to the header
                        .setVisible(true);
            } else if (url.endsWith(".j3.md")) {
                StaticRefs.getDocsProvider().provideDocFrame(url.substring(0, url.length() - 6)).setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
