/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.docs;

import com.j3d.StaticRefs;
import com.j3d.engine.interact.cmd.CommandParser;
import com.j3d.gen.docs.api.ImageTag;
import com.j3d.gen.docs.reader.tokens.wrappers.TWCodeBlock;
import com.j3d.ui.theme.J3DTheme;
import com.j3d.ui.theme.updator.Locator;
import com.j3d.utility.ClipboardUtil;
import com.j3d.utility.Parsing;
import com.j3d.utility.generators.JLabelRichText;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;

/**
 *
 * @author yetnt
 */
public class TextPanel extends javax.swing.JPanel {

    private Locator l;
    private ArrayList<Locator> l2;
    private boolean isCodeblock = false, hasLineNum = true;
    private TWCodeBlock tc;

    /**
     * Creates new form TextPanel
     */
    public TextPanel(String cont) {
        initComponents();
        jLabel1.setText(cont);
        theme();
        setMouseListener();
    }

    public TextPanel(ImageTag imageTag) {
        initComponents();
        jLabel1.setText("");
        File image = imageTag.getImagePath();
        double scale = imageTag.getScale();
        // set the image
        ImageIcon icon = new ImageIcon(image.getAbsolutePath());

        Image scaled = icon.getImage().getScaledInstance(
                (int) (icon.getIconWidth() * scale),
                (int) (icon.getIconHeight() * scale),
                Image.SCALE_SMOOTH
        );

        jLabel1.setIcon(new ImageIcon(scaled));
        theme();
    }

    private void setMouseListener() {
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                super.mouseClicked(e);
                // when clicked twice.
                String originalText;
                if (isCodeblock) {
                    originalText = Parsing.removeHTML(jLabel1.getText().replace(
                            JLabelRichText.LINE_BREAK, "\n"
                    ));
                    if (hasLineNum) {
                        StringBuilder code = new StringBuilder();
                        originalText.lines().forEach(ln -> {
                            // if the lines start with a number followed by a dot, remove it (regex)
                            // regex = (match any number)(match a single dot)(match any length of text after)
                            if (ln.matches("\\d+\\..*")) {
                                code.append(ln.replaceFirst("\\d+\\.", ""));
                            } else {
                                code.append(ln);
                            }
                            code.append("\n");
                        });
                        originalText = code.toString();
                    }
                } else {
                    originalText = Parsing.removeHTML(jLabel1.getText());
                }
                if (e.getClickCount() == 2) {
                    ClipboardUtil.copyToClipboard(originalText.trim());
                    JOptionPane.showMessageDialog(
                            StaticRefs.getMainFrame(),
                            "Text copied to clipboard!",
                            "Copied",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                    if (isCodeblock && tc.isCommand()) {
                        if (StaticRefs.getMainFrame() == null) return; // no main frame, no command parser.
                        CommandParser commandParser = StaticRefs.getCommandParser();
                        if (commandParser.isEmpty()) // we dont wanna override their args.
                            commandParser.setInputField(originalText.trim());
                    }
                }
            }
        });
    }

    public void theme() {
        l2 = J3DTheme.commitAsGenericLbl(jLabel1, false);
        l = J3DTheme.commitAsGenericUi(this);
    }

    public TextPanel asCodeBlock(Color backCol, TWCodeBlock tc, boolean hasLineNum) {
        isCodeblock = true;
        this.tc = tc;
        this.hasLineNum = hasLineNum;
        jLabel1.setFont(
                new Font(Font.MONOSPACED, Font.PLAIN, 14)
        );
        this.setBackground(backCol);
        this.setOpaque(true);
        J3DTheme.themeUpdater.remove(l);
        J3DTheme.themeUpdater.remove(l2);
        if (tc.isCommand())
            this.setToolTipText("Double click this to paste it directly into the command palette!");
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(J3DTheme.UI_SURFACE.color());
        setForeground(J3DTheme.TEXT_PRIMARY.color());
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("dfdff");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
