/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.auth;

import com.j3d.Startup;
import com.j3d.StaticRefs;
import com.j3d.engine.interact.input.keyboard.GlobalKeybinds;
import com.j3d.engine.interact.input.keyboard.KeyBindings;
import com.j3d.storage.db.DatabaseManager;
import com.j3d.storage.db.api.SQLOperator;
import com.j3d.storage.db.users.CUsers;
import com.j3d.storage.db.users.User;
import com.j3d.ui.theme.J3DTheme;
import com.j3d.utility.PasswordHasher;

import javax.swing.*;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class ForgotPassword extends javax.swing.JFrame {

    private final Runnable postPasswordChange;
    private boolean showChar = false;
    private final char echoChar = '•';
    private final KeyBindings ks;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword(Runnable postPasswordChange) {
        initComponents();
        ks = getKeyBindings();
        this.postPasswordChange = postPasswordChange;
        StaticRefs.getLog().uiPrintLn("ForgotPassword completed building");
    }

    private KeyBindings getKeyBindings() {
        final KeyBindings keyBindings = new KeyBindings(
                jPanel1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW),
                jPanel1.getActionMap()
        );
        ks.registerJ3Key(GlobalKeybinds.F1.getKey());
        return keyBindings;
    }

    public ForgotPassword(String email, Runnable postPasswordChange) {
        initComponents();
        ks = getKeyBindings();
        emailTextField.setText(email);
        this.postPasswordChange = postPasswordChange;
        StaticRefs.getLog().uiPrintLn("ForgotPassword completed building");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        applyChange = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        newPasswordField = new javax.swing.JPasswordField();
        seePasswordToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("How did you forget your password already? 😭");
        setBackground(J3DTheme.UI_SURFACE.color());

        jPanel1.setBackground(J3DTheme.UI_SURFACE.color());

        mainLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        mainLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        mainLabel.setText("You forgot...");

        applyChange.setBackground(J3DTheme.BACKGROUND.color());
        applyChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        applyChange.setForeground(J3DTheme.TEXT_PRIMARY.color());
        applyChange.setText("Apply");
        applyChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangeActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        emailLabel.setText("Email (autofilled)");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        passwordLabel.setText("New Password");

        emailTextField.setBackground(J3DTheme.BACKGROUND.color());
        emailTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailTextField.setForeground(J3DTheme.TEXT_PRIMARY.color());

        newPasswordField.setBackground(J3DTheme.BACKGROUND.color());
        newPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newPasswordField.setForeground(J3DTheme.TEXT_PRIMARY.color());

        seePasswordToggleButton.setBackground(J3DTheme.BACKGROUND.color());
        seePasswordToggleButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        seePasswordToggleButton.setText("👁");
        seePasswordToggleButton.setMaximumSize(new java.awt.Dimension(25, 20));
        seePasswordToggleButton.setMinimumSize(new java.awt.Dimension(20, 20));
        seePasswordToggleButton.setPreferredSize(new java.awt.Dimension(25, 20));
        seePasswordToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(applyChange, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(151, 151, 151))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(seePasswordToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mainLabel)
                        .addGap(124, 124, 124))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seePasswordToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(applyChange)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void applyChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangeActionPerformed
        String email = emailTextField.getText();
        char[] password = newPasswordField.getPassword();
        if (email.isEmpty() || password.length == 0) {
            return;
        }

        ArrayList<User> u = DatabaseManager.tblUsers.findWhere(CUsers.EMAIL, SQLOperator.EQUALS, email);
        if (u.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "No user with that email exists.",
                    "J3D Popup",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        User user = u.getFirst();

        try {
            byte[] salt = user.password.salt().getValue();
            String hashedPassword = PasswordHasher.hashPassword(password, salt);

            user.password.hash().setValue(hashedPassword);
            user.save();
        } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
            throw new RuntimeException(e);
        }

        JOptionPane.showMessageDialog(
                null,
                "Password changed successfully!",
                "J3D Popup",
                JOptionPane.INFORMATION_MESSAGE
        );

        this.dispose();
        Startup.run(postPasswordChange);

    }//GEN-LAST:event_applyChangeActionPerformed

    private void seePasswordToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordToggleButtonActionPerformed
        showChar = !showChar;
        newPasswordField.setEchoChar(
            showChar ? (char)0 : echoChar
        );
    }//GEN-LAST:event_seePasswordToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword(
                        () -> {}
                ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyChange;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JToggleButton seePasswordToggleButton;
    // End of variables declaration//GEN-END:variables
}
