 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.auth;

import com.j3d.StaticRefs;
import com.j3d.StaticConfig;
import com.j3d.engine.interact.input.keyboard.GlobalKeybinds;
import com.j3d.engine.interact.input.keyboard.KeyBindings;
import com.j3d.storage.db.users.Password;
import com.j3d.storage.db.users.User;
import com.j3d.storage.db.users.UsersTable;
import com.j3d.ui.theme.CursorManager;
import com.j3d.ui.theme.CursorNames;
import com.j3d.ui.theme.J3DTheme;
import com.j3d.utility.generic.Pair;
import com.j3d.utility.PasswordHasher;

import javax.swing.*;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author ACER
 */
public class Signup extends javax.swing.JFrame {
    
    private boolean showChar = false;
    private final char echoChar = '•';
    private final Runnable postSignup;
    private final ArrayList<KeyBindings> keyBindings = new ArrayList<>();

    /**
     * Creates new form Signup
     */
    public Signup(Runnable postsignup) {
        initComponents();
        keyBindings.add(
                new KeyBindings(
                        jPanel1.getInputMap(),
                        jPanel1.getActionMap(),
                        false
                )
        );
        keyBindings.add(
                new KeyBindings(
                        jPanel2.getInputMap(),
                        jPanel2.getActionMap(),
                        false
                )
        );
        keyBindings.forEach(
                ks -> ks.registerJ3Key(GlobalKeybinds.F1.getKey())
        );
        this.setCursor(CursorManager.get(CursorNames.DEFAULT));
        this.postSignup = postsignup;
        StaticRefs.getLog().uiPrintLn("Signup completed building");
    }

    private boolean validPassword() {

        passwordErrorJLabel.setText(" ");
        repeatPasswordErrorJLabel.setText(" ");

        char[] password = passwordJField.getPassword();
        char[] repeatPassword = repeatPasswordJField.getPassword();

        if (password.length == 0) {
            passwordErrorJLabel.setText("Password cannot be empty");
            return false;
        } else if (password.length < 6) {
            passwordErrorJLabel.setText("Password must be at least 6 characters long");
            return false;
        }

        boolean hasNonAlphaNumeric = false;
        boolean hasCapital = false;
        boolean hasLowercase = false;
        boolean hasNumber = false;
        ArrayList<String> simplePasswords = new ArrayList<>() {{
            add("password");
            add("123");
            add("456");
            add("qwerty");
        }};

        if (
                simplePasswords.stream().map( a -> new String(password).contains(a)).toList().contains(true)
        ) {
            passwordErrorJLabel.setText("Password contains a simple sequence.");
            return false;
        }

        for (char c : password) {
            if (!Character.isLetterOrDigit(c)) {
                hasNonAlphaNumeric = true;
            } else if (Character.isUpperCase(c)) {
                hasCapital = true;
            } else if (Character.isLowerCase(c)){
                hasLowercase = true;
            } else if (Character.isDigit(c)) {
                hasNumber = true;
            }
        }

        if (!hasNonAlphaNumeric) {
            passwordErrorJLabel.setText("Password must contain at least one non-alphanumeric character.");
            return false;
        } else if (!hasCapital) {
            passwordErrorJLabel.setText("Password must contain at least one capital letter.");
            return false;
        } else if (!hasLowercase) {
            passwordErrorJLabel.setText("Password must contain at least one lowercase letter.");
            return false;
        } else if (!hasNumber) {
            passwordErrorJLabel.setText("Password must contain at least one number.");
            return false;
        }

        if (!Arrays.equals(password, repeatPassword)) {
            repeatPasswordErrorJLabel.setText("Passwords do not match.");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newJPanel1 = new com.j3d.ui.auth.ShowcasePanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        nameJField = new javax.swing.JTextField();
        surnameJField = new javax.swing.JTextField();
        emailJField = new javax.swing.JTextField();
        nameJLabel = new javax.swing.JLabel();
        surnameJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        repeatPasswordJLabel = new javax.swing.JLabel();
        passwordJField = new javax.swing.JPasswordField();
        repeatPasswordJField = new javax.swing.JPasswordField();
        seePasswordToggleButton = new javax.swing.JToggleButton();
        enterButton = new javax.swing.JButton();
        nameErrorJLabel = new javax.swing.JLabel();
        surnameErrorJLabel = new javax.swing.JLabel();
        emailErrorJLabel = new javax.swing.JLabel();
        passwordErrorJLabel = new javax.swing.JLabel();
        repeatPasswordErrorJLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J3Engine Signup");
        setIconImage(StaticRefs.logo());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(J3DTheme.BACKGROUND.color());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("J3Engine (J3D)");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\code\\Jaiva3dEngine\\src\\main\\resources\\art\\logo\\J3DiconSmall.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(newJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(newJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel1);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 32780));
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 0));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        getContentPane().add(jSeparator1);

        jPanel2.setBackground(J3DTheme.UI_SURFACE.color());

        nameJField.setBackground(J3DTheme.BACKGROUND.color());
        nameJField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameJField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        nameJField.setToolTipText("");
        nameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJFieldActionPerformed(evt);
            }
        });

        surnameJField.setBackground(J3DTheme.BACKGROUND.color());
        surnameJField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        surnameJField.setForeground(J3DTheme.TEXT_PRIMARY.color());

        emailJField.setBackground(J3DTheme.BACKGROUND.color());
        emailJField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailJField.setForeground(J3DTheme.TEXT_PRIMARY.color());

        nameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameJLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        nameJLabel.setLabelFor(nameJField);
        nameJLabel.setText("Name");

        surnameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        surnameJLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        surnameJLabel.setLabelFor(surnameJField);
        surnameJLabel.setText("Surname");

        emailJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailJLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        emailJLabel.setLabelFor(emailJField);
        emailJLabel.setText("Email");

        passwordJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordJLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        passwordJLabel.setLabelFor(passwordJField);
        passwordJLabel.setText("Password");

        repeatPasswordJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        repeatPasswordJLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        repeatPasswordJLabel.setLabelFor(repeatPasswordJField);
        repeatPasswordJLabel.setText("Repeat Password");

        passwordJField.setBackground(J3DTheme.BACKGROUND.color());
        passwordJField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordJField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        passwordJField.setEchoChar(echoChar);

        repeatPasswordJField.setBackground(J3DTheme.BACKGROUND.color());
        repeatPasswordJField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        repeatPasswordJField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        repeatPasswordJField.setEchoChar(echoChar);

        seePasswordToggleButton.setBackground(J3DTheme.BACKGROUND.color());
        seePasswordToggleButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        seePasswordToggleButton.setText("👁");
        seePasswordToggleButton.setMaximumSize(new java.awt.Dimension(25, 20));
        seePasswordToggleButton.setMinimumSize(new java.awt.Dimension(20, 20));
        seePasswordToggleButton.setPreferredSize(new java.awt.Dimension(25, 20));
        seePasswordToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordToggleButtonActionPerformed(evt);
            }
        });

        enterButton.setBackground(J3DTheme.BACKGROUND.color());
        enterButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enterButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        enterButton.setText("Asambe!");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        nameErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        nameErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        nameErrorJLabel.setText(" ");

        surnameErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        surnameErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        surnameErrorJLabel.setText(" ");
        surnameErrorJLabel.setToolTipText(" ");

        emailErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        emailErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        emailErrorJLabel.setText(" ");

        passwordErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        passwordErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        passwordErrorJLabel.setText(" ");
        passwordErrorJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        repeatPasswordErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        repeatPasswordErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        repeatPasswordErrorJLabel.setText(" ");

        loginButton.setBackground(J3DTheme.BACKGROUND.color());
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        loginButton.setText("Login Instead");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(repeatPasswordErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(surnameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(repeatPasswordJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatPasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordJField)
                                    .addComponent(emailJField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(surnameJField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(nameJField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seePasswordToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surnameErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surnameErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seePasswordToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordJLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordErrorJLabel)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatPasswordJLabel)
                    .addComponent(repeatPasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(repeatPasswordErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(enterButton)
                .addGap(27, 27, 27)
                .addComponent(loginButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seePasswordToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordToggleButtonActionPerformed
        showChar = !showChar;
        passwordJField.setEchoChar(
                showChar ? (char)0 : echoChar
        );
        repeatPasswordJField.setEchoChar(
                showChar ? (char)0 : echoChar
        );
    }//GEN-LAST:event_seePasswordToggleButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        this.setCursor(CursorManager.get(CursorNames.DEFAULT));
        nameErrorJLabel.setText(
                nameJField.getText().isEmpty() ? "You have no name?" : " "
        );
        surnameErrorJLabel.setText(
                surnameJField.getText().isEmpty() ? "You have no surname?" : " "
        );
        emailErrorJLabel.setText(
                emailJField.getText().isEmpty() ? "You have no email?" :
                        !emailJField.getText().contains("@") ? "Invalid email" : " "
        );

        if (!validPassword()) return;

        try {
            byte[] salt = PasswordHasher.generateSalt();
            String hashed = PasswordHasher.hashPassword(passwordJField.getPassword(), salt);
            String name = nameJField.getText();
            String surname = surnameJField.getText();
            String email = emailJField.getText();


            this.setCursor(CursorManager.get(CursorNames.HOURGLASS));
            Pair<Boolean, User> wasRegistered = UsersTable.newOrExisting(
                    name,
                    surname,
                    email,
                    new Password(hashed, salt)
            );
            this.setCursor(CursorManager.get(CursorNames.DEFAULT));
            if (wasRegistered.first) {
                JOptionPane.showMessageDialog(this, "Registered!");
            } else {
                JOptionPane.showMessageDialog(this, "A user with this email already exists", "Registration Failed", JOptionPane.ERROR_MESSAGE);
                return;
            }

            StaticConfig.user = wasRegistered.second;
            this.dispose();
            postSignup.run();

        } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void nameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        Login login = new Login(postSignup);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup(() -> {}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailErrorJLabel;
    private javax.swing.JTextField emailJField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel nameErrorJLabel;
    private javax.swing.JTextField nameJField;
    private javax.swing.JLabel nameJLabel;
    private com.j3d.ui.auth.ShowcasePanel newJPanel1;
    private javax.swing.JLabel passwordErrorJLabel;
    private javax.swing.JPasswordField passwordJField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JLabel repeatPasswordErrorJLabel;
    private javax.swing.JPasswordField repeatPasswordJField;
    private javax.swing.JLabel repeatPasswordJLabel;
    private javax.swing.JToggleButton seePasswordToggleButton;
    private javax.swing.JLabel surnameErrorJLabel;
    private javax.swing.JTextField surnameJField;
    private javax.swing.JLabel surnameJLabel;
    // End of variables declaration//GEN-END:variables
}
