/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.floating.properties.panels;

import com.j3d.Static;
import com.j3d.engine.interact.cmd.CommandsManager;
import com.j3d.gen.properties.Property;
import com.j3d.ui.generic.J3DTheme;
import com.j3d.utility.generators.JLabelRichText;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import static com.j3d.Static.mainFrame;

/**
 *
 * @author yetnt
 */
public class ColourProperty extends javax.swing.JPanel implements PropertyPanel<Color> {

    ArrayList<Property<Color, ?>> properties;
    /**
     * Creates new form StringProperty
     */
    public ColourProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields();
    }

    @Override
    public void setFields() {
        if (singleProperty() || sameColour()) {
            // the colour can safely be extracted from the first element.
            Color col = getSingleProperty().getValueSupplier().get();

            colourPreviewLabel.setText(
                    new JLabelRichText("~".repeat(15))
                            .font(J3DTheme.TEXT_PRIMARY.color(), "4", col)
                            .wrapHTML()
            );
        } else {
            colourPreviewLabel.setText("(multiple values)");
        }
        if (
                getProperties().stream()
                        .anyMatch(Property::isConstant)
        )
            setBtn.setEnabled(false);
    }

    public boolean sameColour() {
        // get the first colour
        Color col = getSingleProperty().getValueSupplier().get();
        // Stream
        return getProperties().stream().allMatch(p ->
                p.getValueSupplier().get().equals(col));
    }

    @Override
    public ArrayList<Property<Color, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colourPreviewLabel = new javax.swing.JLabel();
        setBtn = new javax.swing.JButton();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        colourPreviewLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        colourPreviewLabel.setText("COLOUR LABEL JLBLRICH");

        setBtn.setBackground(J3DTheme.BACKGROUND.color());
        setBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        setBtn.setText(" set");
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colourPreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setBtn)
                    .addComponent(colourPreviewLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
        if (CommandsManager.commandIsRunning()) {
            Static.hoverLabel.error("Finish running command first");
            return;
        }
        Color chosen = JColorChooser.showDialog(
                mainFrame,
                "Choose a colour man",
                getSingleProperty().getValueSupplier().get()
        );
        if (chosen == null) return;
        runAndAddAction(chosen, "Colour");
    }//GEN-LAST:event_setBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colourPreviewLabel;
    private javax.swing.JButton setBtn;
    // End of variables declaration//GEN-END:variables
}
