/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.floating.properties.panels;

import com.j3d.StaticRefs;
import com.j3d.engine.scene.nodes.geometry.*;
import com.j3d.gen.properties.Property;
import com.j3d.ui.theme.J3DTheme;
import com.j3d.utility.generic.Pair;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.UUID;

/**
 *
 * @author yetnt
 */
public class ObjectProperty<T extends GObject> extends JPanel implements PropertyPanel<T> {

    ArrayList<Property<T, ?>> properties;
    /**
     * Creates new form StringProperty
     */
    public ObjectProperty(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields(); //TODO: Implement
    }

    @Override
    public void setFields() {
        // The type of the object reference is guaranteed to be the same whether there is one
        // or multiple.
        // e.g. Tri Leg A will always be a GLine or Line Point B will always be a GPoint
        labelTxtField.setEnabled(false);
        uuidTextField.setEnabled(false);
        Pair<String, UUID> type = setType();
        labelTxtField.setText(type.first);
        if (singleProperty()) {
            uuidTextField.setText(type.second.toString().substring(0, 10) + "...");

            MouseAdapter mouseAdapter = new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (e.getClickCount() == 2) {
                        // add the UUID to the command palette
                        StaticRefs.getCommandParser().injectArgument(
                                type.second
                        );
                    }
                }
            };
            uuidTextField.addMouseListener(mouseAdapter);
            labelTxtField.addMouseListener(mouseAdapter);
        } else {
            uuidTextField.setText("(multiple values)");
        }
    }
    
    private Pair<String, UUID> setType() {
        T t = getSingleProperty().getValueSupplier().get();
        Pair<String, UUID> pair = GObjectRegistry.expectedObjs(
                t,
                null,
                new Pair<>("(point)", UUID.randomUUID()),
                new Pair<>("(line)", UUID.randomUUID()),
                new Pair<>("(tri)", UUID.randomUUID()),
                new Pair<>("(curve)", UUID.randomUUID())
        );
        if (pair == null) {
            throw new IllegalStateException("Unexpected value: " + t);
        }
        return pair;
//        return switch (t) {
//            case GTri t -> new Pair<>("(tri)", t.getId());
//            case GLine l -> new Pair<>("(line)", l.getId());
//            case GPoint p -> new Pair<>("(point)", p.getId());
//            case GCurve c -> new Pair<>("(curve)", c.getId());
//            default ->
//                    throw new IllegalStateException("Unexpected value: " + t);
//        };
    }

    @Override
    public ArrayList<Property<T, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copyBtn = new javax.swing.JButton();
        uuidTextField = new javax.swing.JTextField();
        labelTxtField = new javax.swing.JTextField();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        copyBtn.setBackground(J3DTheme.BACKGROUND.color());
        copyBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        copyBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        copyBtn.setText("copy");
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });

        uuidTextField.setEditable(false);
        uuidTextField.setBackground(J3DTheme.BACKGROUND.color());
        uuidTextField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        uuidTextField.setText("6f099092....");

        labelTxtField.setEditable(false);
        labelTxtField.setBackground(J3DTheme.BACKGROUND.color());
        labelTxtField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTxtField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        labelTxtField.setText("(point)");
        labelTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uuidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uuidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyBtn)
                    .addComponent(labelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelTxtFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_labelTxtFieldActionPerformed
        // Do nbohing
    }//GEN-LAST:event_labelTxtFieldActionPerformed

    private void copyBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        // Copy to user clipboard later maybe.
    }//GEN-LAST:event_copyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyBtn;
    private javax.swing.JTextField labelTxtField;
    private javax.swing.JTextField uuidTextField;
    // End of variables declaration//GEN-END:variables
}
