/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.floating.properties.panels;

import com.j3d.StaticRefs;
import com.j3d.engine.geometry.geo3d.matrix.Vector3;
import com.j3d.engine.interact.cmd.CommandsManager;
import com.j3d.gen.properties.Property;
import com.j3d.ui.theme.J3DTheme;

import java.util.ArrayList;

/**
 *
 * @author yetnt
 */
public class Vector3Property extends javax.swing.JPanel implements PropertyPanel<Vector3> {

    ArrayList<Property<Vector3, ?>> properties;
    public static int ROUND = 2;

    /**
     * Creates new form StringProperty
     */
    public Vector3Property(ArrayList<Property<?, ?>> properties) {
        initComponents();
        this.properties = typeConvert(properties);
        setFields(); //TODO: Implement
    }

    @Override
    public void setFields() {
        if (
                getProperties().stream()
                        .anyMatch(Property::isConstant)
        ) setEnb(false);

        setabelsAndShi(!singleProperty());
    }

    private void setEnb(boolean b) {
        setBtn.setEnabled(b);
    }

    private void setabelsAndShi(boolean multipleValues) {
        if (multipleValues) {
            vector3Preview.setText("(multiple values)");
            return;
        }
        double x = round(getSingleProperty().getValueSupplier().get().getX());
        double y = round(getSingleProperty().getValueSupplier().get().getY());
        double z = round(getSingleProperty().getValueSupplier().get().getZ());

        vector3Preview.setText("(" + x + ", " + y + ", " + z + ")");
    }

    private double round(double val) {
        return (double)((int)(val * ROUND))/ROUND;
    }

    @Override
    public ArrayList<Property<Vector3, ?>> getProperties() {
        return properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBtn = new javax.swing.JButton();
        vector3Preview = new javax.swing.JLabel();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(215, 34));
        setMinimumSize(new java.awt.Dimension(215, 34));

        setBtn.setBackground(J3DTheme.BACKGROUND.color());
        setBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        setBtn.setText("view");
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        vector3Preview.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        vector3Preview.setForeground(J3DTheme.TEXT_PRIMARY.color());
        vector3Preview.setText("LBL FOR VECTOR3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vector3Preview, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vector3Preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
        if (singleProperty()) {
            if (CommandsManager.commandIsRunning()) {
                StaticRefs.getHoverLabel().error("Finish running command first");
                return;
            }
            new Vector3Dialogue(getSingleProperty().getValueSupplier().get(), setBtn);
        }
    }//GEN-LAST:event_setBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton setBtn;
    private javax.swing.JLabel vector3Preview;
    // End of variables declaration//GEN-END:variables
}
