/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.tree;

import java.util.function.Consumer;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author ACER
 */
public class LayerTree extends javax.swing.JPanel {
    
    public static DefaultTreeModel model;
    public static DefaultMutableTreeNode root;

    /**
     * Adds a new node to the tree.
     * @param parent The parent node. If null, the node is added to the root.
     * @param label The label of the node.
     * @param value The value of the node.
     * @param onSelect The action to perform when the node is selected.
     * @return The newly created node.
     * @param <T> The type of the value.
     */
    public <T> DefaultMutableTreeNode addNode(
            DefaultMutableTreeNode parent,
            String label,
            T value,
            Consumer<T> onSelect
    ) {
        if (parent == null)
            parent = root;
        
        TreeNodeIdentity<T> action = new TreeNodeIdentity(label, value, onSelect);
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(action);
        
        model.insertNodeInto(node, parent, parent.getChildCount());
        listJTree.expandPath(new TreePath(parent.getPath()));
        
        return node;
    }

    /**
     * Adds a new node to the tree.
     * @param parent The parent node. If null, the node is added to the root.
     * @param tni The TreeNodeIdentity object containing label, value, and onSelect action.
     * @return The newly created node.
     * @param <T> The type of the value.
     */
    public <T> DefaultMutableTreeNode addNode(
            DefaultMutableTreeNode parent,
            TreeNodeIdentity<T> tni
    ) {
        if (parent == null)
            parent = root;
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(tni);
        model.insertNodeInto(node, parent, parent.getChildCount());
        listJTree.expandPath(new TreePath(parent.getPath()));
        return node;
    }

    /**
     * Removes a node from the tree.
     * @param node The node to remove.
     */
    public void removeNode(DefaultMutableTreeNode node) {
        if (node.getParent() != null) {
            model.removeNodeFromParent(node);
        }
    }

    /**
     * Creates new form List
     */
    public LayerTree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listJTree = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Layers");
        listJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        root = treeNode1;
        model = (DefaultTreeModel) listJTree.getModel();

        listJTree.addTreeSelectionListener(
            e -> {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) listJTree.getLastSelectedPathComponent();

                if (node == null) return;

                Object obj = node.getUserObject();
                if (obj instanceof TreeNodeIdentity tni) {
                    if (tni.onSelect != null)
                    tni.onSelect.accept(tni.value);
                }
            });
            jScrollPane1.setViewportView(listJTree);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTree listJTree;
    // End of variables declaration//GEN-END:variables
}
