package com.j3d.engine.geometry.geo3d.rot;

import com.j3d.engine.geometry.geo3d.matrix.Matrix3;
import com.j3d.engine.geometry.geo3d.matrix.MatrixInterface;
import com.j3d.engine.geometry.geo3d.matrix.MatrixMath;

/**
 * Implements the {@link RotationMatrixDirection} interface to create rotation matrices
 * that transform a direction from world space to camera space.
 * <p>
 * This is the inverse of the standard camera transformation. It's used to determine
 * how world-space objects and directions should appear relative to the camera's viewpoint.
 * For example, this is essential for the rendering pipeline where all world objects
 * are transformed into the camera's local coordinate system before projection.
 * <p>
 * The matrices generated by this class are the transpose (and thus the inverse) of the
 * matrices from {@link CamToWorldDirection}. The order of multiplication is also reversed,
 * typically becoming {@code M = Roll * Pitch * Yaw}.
 */
public class WorldToCamDirection implements RotationMatrixDirection {

    final private double pitch, yaw, roll;

    /**
     * Constructs a new {@code WorldToCamDirection} transformer.
     *
     * @param pitch The pitch angle in radians (rotation around the X-axis).
     * @param yaw   The yaw angle in radians (rotation around the Y-axis).
     * @param roll  The roll angle in radians (rotation around the Z-axis).
     */
    public WorldToCamDirection(double pitch, double yaw, double roll) {
        this.pitch = pitch;
        this.yaw = yaw;
        this.roll = roll;
    }

    /**
     * Creates an inverse rotation matrix for pitch (rotation around the X-axis).
     * This is the transpose of the standard pitch matrix.
     *
     * @return A 3x3 {@link MatrixInterface} for inverse pitch rotation.
     */
    @Override
    public Matrix3 rotPitch() {
        double c = Math.cos(pitch);
        double s = Math.sin(pitch);
        return Matrix3.of(MatrixMath.matrixOf(
                new double[][]{
                        {1, 0, 0},
                        {0, c, s},
                        {0, -s, c}
                }
        ));
    }

    /**
     * Creates an inverse rotation matrix for yaw (rotation around the Y-axis).
     * This is the transpose of the standard yaw matrix.
     *
     * @return A 3x3 {@link MatrixInterface} for inverse yaw rotation.
     */
    @Override
    public Matrix3 rotYaw() {
        double c = Math.cos(yaw);
        double s = Math.sin(yaw);
        return Matrix3.of(MatrixMath.matrixOf(
                new double[][]{
                        {c, 0, -s},
                        {0, 1, 0},
                        {s, 0, c}
                }
        ));
    }

    /**
     * Creates an inverse rotation matrix for roll (rotation around the Z-axis).
     * This is the transpose of the standard roll matrix.
     *
     * @return A 3x3 {@link MatrixInterface} for inverse roll rotation.
     */
    @Override
    public Matrix3 rotRoll() {
        double c = Math.cos(roll);
        double s = Math.sin(roll);
        return Matrix3.of(MatrixMath.matrixOf(
                new double[][]{
                        {c, s, 0},
                        {-s, c, 0},
                        {0, 0, 1}
                }
        ));
    }

    @Override
    public Matrix3 matrix() {
        return Matrix3.of(MatrixMath.mult(
                MatrixMath.mult(
                        rotPitch(), rotYaw()
                ),
                rotRoll()
        ));
    }
}
