/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.j3d.ui.dialog;
import com.j3d.engine.interact.input.keyboard.KeyBindings;
import com.j3d.ui.theme.J3DTheme;

import javax.swing.*;
import java.awt.event.InputEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author yetnt
 */
public class JKeyChooser extends javax.swing.JDialog {
    
    enum Modifiers {
        CTRL(InputEvent.CTRL_DOWN_MASK, "Ctrl"),
        SHIFT(InputEvent.SHIFT_DOWN_MASK, "Shift"),
        ALT(InputEvent.ALT_DOWN_MASK, "Alt"),
        ALT_GRAPH(InputEvent.ALT_GRAPH_DOWN_MASK, "Alt Gr"),
        META(InputEvent.META_DOWN_MASK, "Meta");

        private final int mask;
        private final String name;
        Modifiers(int mask, String name) {
            this.mask = mask;
            this.name = name;
        }

        public static EnumSet<Modifiers> fromKeyStroke(int modifiers) {
            EnumSet<Modifiers> ret = EnumSet.noneOf(Modifiers.class);

            for (Modifiers m : Modifiers.values()) {
                if ((modifiers & m.mask) != 0) {
                    ret.add(m);
                }
            }
            return ret;
        }

        public static int toMask(EnumSet<Modifiers> mods) {
            int mask = 0;
            for (Modifiers m : mods) {
                mask |= m.mask;
            }
            return mask;
        }
    }

    EnumSet<Modifiers> modifiers = EnumSet.of(Modifiers.CTRL);
    int keyCode = KeyEvent.VK_A; // default
    HashMap<Modifiers, JCheckBox> checkboxes = new HashMap<>();
    KeyStroke finalKeyStroke;

    /**
     * Creates new form JKeyChooser
     */
    public JKeyChooser(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        shortcuts();
        setInputField();
        setModifiersCheckboxes();
        shortcutTextFieldInputHandling();
        this.setVisible(true);
    }

    public JKeyChooser(JFrame parent, KeyStroke existingKeyStroke) {
        super(parent, true);
        initComponents();
        modifiers = Modifiers.fromKeyStroke(existingKeyStroke.getModifiers());
        keyCode = existingKeyStroke.getKeyCode();
        shortcuts();
        setInputField();
        setModifiersCheckboxes();
        shortcutTextFieldInputHandling();
        this.setVisible(true);
    }

    private void shortcuts() {
        checkboxes.put(Modifiers.CTRL, ctrlCheckBox);
        checkboxes.put(Modifiers.SHIFT, shiftCheckBox);
        checkboxes.put(Modifiers.ALT, altCheckBox);
        checkboxes.put(Modifiers.ALT_GRAPH, altGraphCheckBox);
        checkboxes.put(Modifiers.META, metaCheckBox);
    }

    private void setModifiersCheckboxes() {
        for (Map.Entry<Modifiers, JCheckBox> entry : checkboxes.entrySet()) {
            if (modifiers.contains(entry.getKey()))
                entry.getValue().setSelected(true);
            else
                entry.getValue().setSelected(false);
        }
    }

    private void setInputField() {
        String mods = modifiers
                .stream()
                .reduce("",
                        (m1, m2) -> {
                            return m1 + (m1.isBlank() ? "" : "+") + m2.name;
                        },
                        (s, e) -> {
                            return s + e;
                        }
                        );
        String key = getKeyText();

        shortcutTextField.setText(mods + " " + key);
    }

    private String getKeyText() {
        String t = KeyEvent.getKeyText(keyCode);
        if (!List.of("Shift", "Ctrl", "Alt", "Meta").contains(t))
            return t;
        return "";
    }

    private void shortcutTextFieldInputHandling() {
        shortcutTextField.setEditable(false);
        shortcutTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                modifiers = Modifiers.fromKeyStroke(e.getModifiersEx());
                keyCode = e.getKeyCode();
                setModifiersCheckboxes();
                setInputField();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        shortcutTextField = new javax.swing.JTextField();
        altCheckBox = new javax.swing.JCheckBox();
        ctrlCheckBox = new javax.swing.JCheckBox();
        shiftCheckBox = new javax.swing.JCheckBox();
        metaCheckBox = new javax.swing.JCheckBox();
        altGraphCheckBox = new javax.swing.JCheckBox();
        clearShortcut = new javax.swing.JButton();
        setShortcut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(J3DTheme.UI_SURFACE.color());

        jPanel1.setBackground(J3DTheme.UI_SURFACE.color());

        jLabel1.setBackground(J3DTheme.BACKGROUND.color());
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setText("Input a keyboard shortcut combination within the input field below:");

        shortcutTextField.setBackground(J3DTheme.BACKGROUND.color());
        shortcutTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        shortcutTextField.setForeground(J3DTheme.TEXT_PRIMARY.color());
        shortcutTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shortcutTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        shortcutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcutTextFieldActionPerformed(evt);
            }
        });

        altCheckBox.setBackground(J3DTheme.BACKGROUND.color());
        altCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        altCheckBox.setText("Alt");
        altCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altCheckBoxActionPerformed(evt);
            }
        });

        ctrlCheckBox.setBackground(J3DTheme.BACKGROUND.color());
        ctrlCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        ctrlCheckBox.setText("Ctrl");
        ctrlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlCheckBoxActionPerformed(evt);
            }
        });

        shiftCheckBox.setBackground(J3DTheme.BACKGROUND.color());
        shiftCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        shiftCheckBox.setText("Shift");
        shiftCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftCheckBoxActionPerformed(evt);
            }
        });

        metaCheckBox.setBackground(J3DTheme.BACKGROUND.color());
        metaCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        metaCheckBox.setText("Meta (Mac Only)");
        metaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metaCheckBoxActionPerformed(evt);
            }
        });

        altGraphCheckBox.setBackground(J3DTheme.BACKGROUND.color());
        altGraphCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        altGraphCheckBox.setText("Alt Graph");
        altGraphCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altGraphCheckBoxActionPerformed(evt);
            }
        });

        clearShortcut.setBackground(J3DTheme.BACKGROUND.color());
        clearShortcut.setForeground(J3DTheme.TEXT_PRIMARY.color());
        clearShortcut.setText("Clear");
        clearShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearShortcutActionPerformed(evt);
            }
        });

        setShortcut.setBackground(J3DTheme.BACKGROUND.color());
        setShortcut.setForeground(J3DTheme.TEXT_PRIMARY.color());
        setShortcut.setText("Set");
        setShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setShortcutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(altCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctrlCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shiftCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(metaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altGraphCheckBox)
                        .addGap(59, 59, 59))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(shortcutTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shortcutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altCheckBox)
                    .addComponent(ctrlCheckBox)
                    .addComponent(shiftCheckBox)
                    .addComponent(metaCheckBox)
                    .addComponent(altGraphCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearShortcut)
                    .addComponent(setShortcut))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altCheckBoxActionPerformed
        if (altCheckBox.isSelected())
            modifiers.add(Modifiers.ALT);
        else
            modifiers.remove(Modifiers.ALT);
        setInputField();
    }//GEN-LAST:event_altCheckBoxActionPerformed

    private void ctrlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlCheckBoxActionPerformed
        if (ctrlCheckBox.isSelected())
            modifiers.add(Modifiers.CTRL);
        else
            modifiers.remove(Modifiers.CTRL);
        setInputField();
    }//GEN-LAST:event_ctrlCheckBoxActionPerformed

    private void shiftCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftCheckBoxActionPerformed
        if (shiftCheckBox.isSelected())
            modifiers.add(Modifiers.SHIFT);
        else
            modifiers.remove(Modifiers.SHIFT);
        setInputField();
    }//GEN-LAST:event_shiftCheckBoxActionPerformed

    private void metaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metaCheckBoxActionPerformed
        if (metaCheckBox.isSelected())
            modifiers.add(Modifiers.META);
        else
            modifiers.remove(Modifiers.META);
        setInputField();
    }//GEN-LAST:event_metaCheckBoxActionPerformed

    private void altGraphCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altGraphCheckBoxActionPerformed
        if (altGraphCheckBox.isSelected())
            modifiers.add(Modifiers.ALT_GRAPH);
        else
            modifiers.remove(Modifiers.ALT_GRAPH);
        setInputField();
    }//GEN-LAST:event_altGraphCheckBoxActionPerformed

    private void shortcutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcutTextFieldActionPerformed
        // e
    }//GEN-LAST:event_shortcutTextFieldActionPerformed

    private void clearShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearShortcutActionPerformed
        modifiers.clear();
        keyCode = KeyEvent.VK_A;
        setModifiersCheckboxes();
        setInputField();
    }//GEN-LAST:event_clearShortcutActionPerformed

    private void setShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setShortcutActionPerformed
        finalKeyStroke = KeyStroke.getKeyStroke(
                keyCode, Modifiers.toMask(modifiers)
        );
        if (List.of(KeyEvent.VK_SHIFT, KeyEvent.VK_CONTROL, KeyEvent.VK_ALT, KeyEvent.VK_META, KeyEvent.VK_ALT_GRAPH).contains(finalKeyStroke.getKeyCode())){
            JOptionPane.showMessageDialog(getParent(), "Press another key with the modifier");
        } else if (KeyBindings.getGlobalKeyStrokes().contains(finalKeyStroke)) {
            JOptionPane.showMessageDialog(getParent(), "J3Engine lowk already uses that key stroke combination for something");
        } else
            dispose();

    }//GEN-LAST:event_setShortcutActionPerformed

    public KeyStroke getFinalKeyStroke() {
        return finalKeyStroke;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JKeyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JKeyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JKeyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JKeyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JKeyChooser dialog = new JKeyChooser(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox altCheckBox;
    private javax.swing.JCheckBox altGraphCheckBox;
    private javax.swing.JButton clearShortcut;
    private javax.swing.JCheckBox ctrlCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox metaCheckBox;
    private javax.swing.JButton setShortcut;
    private javax.swing.JCheckBox shiftCheckBox;
    private javax.swing.JTextField shortcutTextField;
    // End of variables declaration//GEN-END:variables
}
