/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.home;

import com.j3d.Startup;
import com.j3d.Static;
import com.j3d.storage.files.util.ProjectImagePair;
import com.j3d.ui.J3DTheme;
import com.j3d.utility.ImageUtils;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.stream.Collectors;

/**
 *
 * @author ACER
 */
public class Projects extends javax.swing.JFrame {

    HashSet<ProjectButton> pinned = new HashSet<>();

    /**
     * Creates new form Projects
     */
    public Projects() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                Static.engineFiles.pinned.writeProjs(
                        pinned.stream()
                                .map(ProjectButton::getIdentity)
                                .collect(Collectors.toCollection(HashSet::new))
                );
            }
        });
    }

    public ImageIcon scaleImage(File image) {
        return ImageUtils.createCroppedIcon2(image, 37, 16, 4);
    }

    public void genericLoad(ArrayList<ProjectImagePair> projs, JPanel targetPanel, boolean pin) {
            for (ProjectImagePair proj : projs) {
                File image = proj.getProjectImage();
                File project = proj.getProjectFile();
                ProjectButton pb = new ProjectButton(proj, scaleImage(image), project.getName(), this, targetPanel);
                if (pin) {
                    pb.setPinned(true);
                    pinned.add(pb);
                }
                if (!targetPanel.equals(pinnedProjectsPanel)) {
                    ArrayList<ProjectButton> copy = pinned.stream().filter(
                            p -> ProjectImagePair.isCopy(p.identity, proj)
                    ).collect(Collectors.toCollection(ArrayList::new));
                    if (!copy.isEmpty()) {
                        pb.setDuplicate(copy.getFirst());
                    }
                }
                targetPanel.add(pb);
                targetPanel.add(pb.filler());
            }
    }

    public void loadRecentProjects() {
        ArrayList<ProjectImagePair> projs = Static.engineFiles.recents.readRecents();
        genericLoad(projs, recentProjectsPanel, false);
    }

    public void loadPinnedProjects() {
        ArrayList<ProjectImagePair> projs = Static.engineFiles.pinned.readPinned();
        genericLoad(projs, pinnedProjectsPanel, true);
    }

    public void loadStarterProjects() {
        StaticProjectButton freshProject = new StaticProjectButton("Fresh Project", e -> {
            Startup.engine(false);
            dispose();
        });
        StaticProjectButton debugScene = new StaticProjectButton("Debug Project", e -> {
            Startup.engine(true);
            dispose();
        });
        starterProjectsPanel.add(freshProject);
        starterProjectsPanel.add(freshProject.filler());
        starterProjectsPanel.add(debugScene);
        starterProjectsPanel.add(debugScene.filler());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollpanepanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pinnedProjectsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        starterProjectsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        recentProjectsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Static.logo());
        setMaximumSize(new java.awt.Dimension(16, 2147483647));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Weclome Name!");

        jLabel5.setText("Create a project or a starter project to get started");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        scrollpanepanel.setBackground(J3DTheme.UI_SURFACE.color());
        scrollpanepanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setMaximumSize(new java.awt.Dimension(327, 300));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(120, 20));

        pinnedProjectsPanel.setBackground(J3DTheme.UI_SURFACE.color());
        pinnedProjectsPanel.setMaximumSize(new java.awt.Dimension(327, 300));
        pinnedProjectsPanel.setMinimumSize(new java.awt.Dimension(120, 20));
        pinnedProjectsPanel.setPreferredSize(new java.awt.Dimension(120, 20));
        pinnedProjectsPanel.setLayout(new javax.swing.BoxLayout(pinnedProjectsPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane3.setViewportView(pinnedProjectsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 782;
        gridBagConstraints.ipady = 168;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 12, 6);
        scrollpanepanel.add(jScrollPane3, gridBagConstraints);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(327, 300));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(120, 20));

        starterProjectsPanel.setBackground(J3DTheme.UI_SURFACE.color());
        starterProjectsPanel.setMaximumSize(new java.awt.Dimension(327, 300));
        starterProjectsPanel.setMinimumSize(new java.awt.Dimension(120, 20));
        starterProjectsPanel.setPreferredSize(new java.awt.Dimension(120, 20));
        starterProjectsPanel.setLayout(new javax.swing.BoxLayout(starterProjectsPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(starterProjectsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 782;
        gridBagConstraints.ipady = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 6);
        scrollpanepanel.add(jScrollPane2, gridBagConstraints);

        jScrollPane4.setMaximumSize(new java.awt.Dimension(327, 300));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(120, 20));

        recentProjectsPanel.setBackground(J3DTheme.UI_SURFACE.color());
        recentProjectsPanel.setMaximumSize(new java.awt.Dimension(327, 300));
        recentProjectsPanel.setMinimumSize(new java.awt.Dimension(120, 20));
        recentProjectsPanel.setPreferredSize(new java.awt.Dimension(120, 20));
        recentProjectsPanel.setLayout(new javax.swing.BoxLayout(recentProjectsPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane4.setViewportView(recentProjectsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 780;
        gridBagConstraints.ipady = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        scrollpanepanel.add(jScrollPane4, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setText("Pinned Projects");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 195;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 0, 0);
        scrollpanepanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel2.setText("Get Started");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        scrollpanepanel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel3.setText("Recent Projects");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        scrollpanepanel.add(jLabel3, gridBagConstraints);

        jScrollPane1.setViewportView(scrollpanepanel);

        getContentPane().add(jScrollPane1);
        loadPinnedProjects();
        loadRecentProjects();
        loadStarterProjects();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JPanel pinnedProjectsPanel;
    public javax.swing.JPanel recentProjectsPanel;
    private javax.swing.JPanel scrollpanepanel;
    public javax.swing.JPanel starterProjectsPanel;
    // End of variables declaration//GEN-END:variables
}
