/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.home;

import com.j3d.Static;
import com.j3d.settings.CoreSettings;
import com.j3d.storage.db.users.Password;
import com.j3d.storage.db.users.User;
import com.j3d.storage.db.users.UsersTable;
import com.j3d.ui.CursorManager;
import com.j3d.ui.CursorNames;
import com.j3d.utility.Pair;
import com.j3d.utility.PasswordHasher;

import javax.swing.*;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author ACER
 */
public class Signup extends javax.swing.JFrame {
    
    private boolean showChar = false;
    private final char echoChar = '•';
    private final Runnable postSignup;

    /**
     * Creates new form Signup
     */
    public Signup(Runnable postsignup) {
        initComponents();
        this.setCursor(CursorManager.get(CursorNames.DEFAULT));
        this.postSignup = postsignup;
    }

    private boolean validPassword() {

        passwordErrorJLabel.setText(" ");
        repeatPasswordErrorJLabel.setText(" ");

        char[] password = passwordJField.getPassword();
        char[] repeatPassword = repeatPasswordJField.getPassword();

        if (password.length == 0) {
            passwordErrorJLabel.setText("Password cannot be empty");
            return false;
        } else if (password.length < 6) {
            passwordErrorJLabel.setText("Password must be at least 6 characters long");
            return false;
        }

        boolean hasNonAlphaNumeric = false;
        boolean hasCapital = false;
        boolean hasLowercase = false;
        boolean hasNumber = false;
        ArrayList<String> simplePasswords = new ArrayList<>() {{
            add("password");
            add("123");
            add("456");
            add("qwerty");
        }};

        if (
                simplePasswords.stream().map( a -> new String(password).contains(a)).toList().contains(true)
        ) {
            passwordErrorJLabel.setText("Password contains a simple sequence.");
            return false;
        }

        for (char c : password) {
            if (!Character.isLetterOrDigit(c)) {
                hasNonAlphaNumeric = true;
            } else if (Character.isUpperCase(c)) {
                hasCapital = true;
            } else if (Character.isLowerCase(c)){
                hasLowercase = true;
            } else if (Character.isDigit(c)) {
                hasNumber = true;
            }
        }

        if (!hasNonAlphaNumeric) {
            passwordErrorJLabel.setText("Password must contain at least one non-alphanumeric character.");
            return false;
        } else if (!hasCapital) {
            passwordErrorJLabel.setText("Password must contain at least one capital letter.");
            return false;
        } else if (!hasLowercase) {
            passwordErrorJLabel.setText("Password must contain at least one lowercase letter.");
            return false;
        } else if (!hasNumber) {
            passwordErrorJLabel.setText("Password must contain at least one number.");
            return false;
        }

        if (!Arrays.equals(password, repeatPassword)) {
            repeatPasswordErrorJLabel.setText("Passwords do not match.");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        nameJField = new javax.swing.JTextField();
        surnameJField = new javax.swing.JTextField();
        emailJField = new javax.swing.JTextField();
        nameJLabel = new javax.swing.JLabel();
        surnameJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        repeatPasswordJLabel = new javax.swing.JLabel();
        passwordJField = new javax.swing.JPasswordField();
        repeatPasswordJField = new javax.swing.JPasswordField();
        seePasswordToggleButton = new javax.swing.JToggleButton();
        enterButton = new javax.swing.JButton();
        nameErrorJLabel = new javax.swing.JLabel();
        surnameErrorJLabel = new javax.swing.JLabel();
        emailErrorJLabel = new javax.swing.JLabel();
        passwordErrorJLabel = new javax.swing.JLabel();
        repeatPasswordErrorJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(Static.logo());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("J3Engine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 600));
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 0));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        getContentPane().add(jSeparator1);

        nameJField.setToolTipText("");
        nameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJFieldActionPerformed(evt);
            }
        });

        nameJLabel.setLabelFor(nameJField);
        nameJLabel.setText("Name");

        surnameJLabel.setLabelFor(surnameJField);
        surnameJLabel.setText("Surname");

        emailJLabel.setLabelFor(emailJField);
        emailJLabel.setText("Email");

        passwordJLabel.setLabelFor(passwordJField);
        passwordJLabel.setText("Password");

        repeatPasswordJLabel.setLabelFor(repeatPasswordJField);
        repeatPasswordJLabel.setText("Repeat Password");

        passwordJField.setEchoChar(echoChar);

        repeatPasswordJField.setEchoChar(echoChar);

        seePasswordToggleButton.setText("👁");
        seePasswordToggleButton.setMaximumSize(new java.awt.Dimension(25, 20));
        seePasswordToggleButton.setMinimumSize(new java.awt.Dimension(20, 20));
        seePasswordToggleButton.setPreferredSize(new java.awt.Dimension(25, 20));
        seePasswordToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordToggleButtonActionPerformed(evt);
            }
        });

        enterButton.setText("Asambe!");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        nameErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        nameErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        nameErrorJLabel.setText(" ");

        surnameErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        surnameErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        surnameErrorJLabel.setText(" ");
        surnameErrorJLabel.setToolTipText(" ");

        emailErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        emailErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        emailErrorJLabel.setText(" ");

        passwordErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        passwordErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        passwordErrorJLabel.setText(" ");
        passwordErrorJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        repeatPasswordErrorJLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        repeatPasswordErrorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        repeatPasswordErrorJLabel.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(repeatPasswordErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(emailJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(surnameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordJField)
                                    .addComponent(emailJField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(surnameJField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(nameJField)
                                    .addComponent(nameErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(surnameErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailErrorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seePasswordToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(repeatPasswordJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(repeatPasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surnameErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seePasswordToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordJLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatPasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeatPasswordJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatPasswordErrorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(enterButton)
                .addGap(101, 101, 101))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seePasswordToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordToggleButtonActionPerformed
        showChar = !showChar;
        passwordJField.setEchoChar(
                showChar ? (char)0 : echoChar
        );
        repeatPasswordJField.setEchoChar(
                showChar ? (char)0 : echoChar
        );
    }//GEN-LAST:event_seePasswordToggleButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        this.setCursor(CursorManager.get(CursorNames.DEFAULT));
        nameErrorJLabel.setText(
                nameJField.getText().isEmpty() ? "You have no name?" : " "
        );
        surnameErrorJLabel.setText(
                surnameJField.getText().isEmpty() ? "You have no surname?" : " "
        );
        emailErrorJLabel.setText(
                emailJField.getText().isEmpty() ? "You have no email?" :
                        !emailJField.getText().contains("@") ? "Invalid email" : " "
        );

        if (!validPassword()) return;

        try {
            byte[] salt = PasswordHasher.generateSalt();
            String hashed = PasswordHasher.hashPassword(passwordJField.getPassword(), salt);
            String name = nameJField.getText();
            String surname = surnameJField.getText();
            String email = emailJField.getText();

            try {
                this.setCursor(CursorManager.get(CursorNames.HOURGLASS));
                Pair<Boolean, User> wasRegistered = UsersTable.newOrExisting(
                        name,
                        surname,
                        email,
                        new Password(hashed, salt)
                );
                this.setCursor(CursorManager.get(CursorNames.DEFAULT));
                if (wasRegistered.first) {
                    JOptionPane.showMessageDialog(this, "Registered!");
                } else {
                    JOptionPane.showMessageDialog(this, "A user with this email already exists", "Registration Failed", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                CoreSettings.user = wasRegistered.second;
                this.dispose();
                postSignup.run();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "A db error occurred", "err", JOptionPane.ERROR_MESSAGE);
                throw new RuntimeException(e);
            }

        } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void nameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup(() -> {}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailErrorJLabel;
    private javax.swing.JTextField emailJField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameErrorJLabel;
    private javax.swing.JTextField nameJField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel passwordErrorJLabel;
    private javax.swing.JPasswordField passwordJField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JLabel repeatPasswordErrorJLabel;
    private javax.swing.JPasswordField repeatPasswordJField;
    private javax.swing.JLabel repeatPasswordJLabel;
    private javax.swing.JToggleButton seePasswordToggleButton;
    private javax.swing.JLabel surnameErrorJLabel;
    private javax.swing.JTextField surnameJField;
    private javax.swing.JLabel surnameJLabel;
    // End of variables declaration//GEN-END:variables
}
