/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.home;


import javax.swing.*;
import java.awt.*;

import com.j3d.ui.CursorManager;
import com.j3d.ui.CursorNames;
import com.j3d.ui.J3DTheme;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.function.Consumer;

/**
 *
 * @author ACER
 */
public class StaticProjectButton extends javax.swing.JPanel {

    Box.Filler filler = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 10), new java.awt.Dimension(30, 10));
    Consumer<MouseEvent> action;

    /**
     * Creates new form ProjectButton
     */
    public StaticProjectButton(String name, Consumer<MouseEvent> action) {
        initComponents();
        projectImageLabel.setText(name);
        projectImageLabel.setCursor(CursorManager.get(CursorNames.HAND_POINTER));
        projectName.setText(name);
        this.action = action;
        complete();
    }

    public Component filler() {
        return filler;
    }

    public void complete() {
        projectImageLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    action.accept(e);
                } else if (e.getClickCount() == 1) {
                    // None.
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectName = new javax.swing.JLabel();
        projectImageLabel = new javax.swing.JLabel();

        setBackground(J3DTheme.UI_SURFACE.color());
        setMaximumSize(new java.awt.Dimension(174, 174));
        setMinimumSize(new java.awt.Dimension(174, 174));
        setPreferredSize(new java.awt.Dimension(174, 174));

        projectName.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        projectName.setForeground(J3DTheme.TEXT_PRIMARY.color());
        projectName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectName.setText("jLabel4");

        projectImageLabel.setBackground(J3DTheme.ACCENT_SECONDARY.color());
        projectImageLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        projectImageLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        projectImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectImageLabel.setText("jLabel4");
        projectImageLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
            .addComponent(projectImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projectImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectName))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel projectImageLabel;
    private javax.swing.JLabel projectName;
    // End of variables declaration//GEN-END:variables
}
