/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.j3d.ui.settings.popouts.macros;
import com.j3d.engine.interact.macros.Macro;
import com.j3d.ui.theme.J3DTheme;

import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.Collectors;

import com.j3d.StaticRefs;

import javax.swing.*;

/**
 *
 * @author yetnt
 */
public class MacrosEditor extends javax.swing.JDialog {

    ArrayList<MacroWrapper> wrappers = new ArrayList<>();

    /**
     * Creates new form MacrosEditor
     */
    public MacrosEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        HashMap<String, Macro> map = StaticRefs.getMacroUtils().getMacros();
        Map<KeyStroke, String> keyStrokes = StaticRefs
                .getMacroUtils()
                .getMacroKeys()
                .entrySet()
                .stream()
                .filter(
                        (entry) -> {
                            // if the entry doesn't exist within the map, this key's file was deleted so skip it.
                            return map.containsKey(entry.getValue());
                        }
                ).collect(
                        Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)
                );

        Set<Macro> withoutKeys = map.entrySet().stream()
                .filter((k) -> !keyStrokes.containsValue(k.getKey()))
                .map(Map.Entry::getValue)
                .collect(
                        Collectors.toSet()
                );

        keyStrokes.forEach((k, v) -> wrappers.add(new MacroWrapper(v, k)));
        withoutKeys.forEach(m -> wrappers.add(new MacroWrapper(m.getName(), null)));

        wrappers.forEach(wrap -> macrosPanel.add(new MacroPanel(wrap)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        macrosPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(J3DTheme.UI_SURFACE.color());

        jScrollPane1.setBackground(J3DTheme.UI_SURFACE.color());

        macrosPanel.setBackground(J3DTheme.UI_SURFACE.color());
        macrosPanel.setLayout(new javax.swing.BoxLayout(macrosPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(macrosPanel);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Macros Editor");

        saveBtn.setBackground(J3DTheme.BACKGROUND.color());
        saveBtn.setForeground(J3DTheme.TEXT_PRIMARY.color()
        );
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(J3DTheme.BACKGROUND.color());
        jButton2.setForeground(J3DTheme.TEXT_PRIMARY.color()
        );
        jButton2.setText("Random Button That do nun");

        cancelBtn.setBackground(J3DTheme.BACKGROUND.color());
        cancelBtn.setForeground(J3DTheme.TEXT_PRIMARY.color()
        );
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(jButton2)
                    .addComponent(cancelBtn))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        HashSet<KeyStroke> keyStrokes = new HashSet<>();
        HashMap<KeyStroke, String> map = new HashMap<>();
        AtomicBoolean collision = new AtomicBoolean(false);
        wrappers.forEach(wrapper -> {
            if (wrapper.getKeyStroke() != null) {
                if (keyStrokes.contains(wrapper.getKeyStroke())) {
                    JOptionPane.showMessageDialog(
                            StaticRefs.getMainFrame(),
                            "There is a keystroke collision for the following key:\n"
                            + "-> " + wrapper.getKeyStroke().toString(),
                            "Keystroke Collision",
                            JOptionPane.ERROR_MESSAGE
                    );
                    collision.set(true);
                    return;
                }
                keyStrokes.add(wrapper.getKeyStroke());
                map.put(wrapper.getKeyStroke(), wrapper.getIdentity());
            }
        });

        if (collision.get()) return;

        StaticRefs.getMacroUtils().setMacroKeys(map);

        dispose();

    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MacrosEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MacrosEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MacrosEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MacrosEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MacrosEditor dialog = new MacrosEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel macrosPanel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
