/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.popups;

import com.j3d.Executor;
import com.j3d.J3DSettings;
import com.j3d.Static;
import com.j3d.engine.SceneManager;
import com.j3d.engine.layer.Layer;
import com.j3d.engine.draw.tris.TriangleSortMethod;
import com.j3d.engine.geometry.geo2d.graphics.GPoint;
import com.j3d.engine.geometry.geo2d.graphics.GTri;
import com.j3d.engine.geometry.geo3d.Thing;
import com.j3d.engine.geometry.geo3d.matrix.Vector3;
import com.j3d.ui.J3DTheme;
import com.j3d.ui.engine.FloatingPanel;

import javax.swing.*;
import java.awt.*;
import java.util.Random;

/**
 *
 * @author ACER
 */
public class DebugPanel extends javax.swing.JPanel {

    public Executor executor = null;
    public SceneManager sceneManager = null;
    public Frame frame = null;
    public FloatingPanel floatingPanel = new FloatingPanel("Debug Panel");

    /**
     * Creates new form NewJPanel
     */
    public DebugPanel() {
        initComponents();
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this); // 'this' refers to the panel
        } catch (Exception e) {
            e.printStackTrace();
        }
        floatingPanel.finish(this, (c) -> {});
    }

    public void toggleHidden() {
        floatingPanel.toggleHidden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortMethodButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        randomTriBtn = new javax.swing.JButton();
        debugLabel = new javax.swing.JLabel();
        drawLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        logLabel = new javax.swing.JLabel();
        sliderYaw = new javax.swing.JSlider();
        sliderPitch = new javax.swing.JSlider();
        sliderRoll = new javax.swing.JSlider();
        camRotationLabel1 = new javax.swing.JLabel();
        YawLabel = new javax.swing.JLabel();
        PitchLabel = new javax.swing.JLabel();
        RollLabel = new javax.swing.JLabel();
        NoneRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        showTriDistCheckBox = new javax.swing.JCheckBox();
        showTriDepthCheckBox = new javax.swing.JCheckBox();
        showTriNormalsCheckBox = new javax.swing.JCheckBox();
        BucketSortRadio = new javax.swing.JRadioButton();
        CamDistSortRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        backFaceCullingCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        visibleSortRadioButton = new javax.swing.JRadioButton();
        camDepthSortRadioButton = new javax.swing.JRadioButton();
        DDUUIDSortRadioButton = new javax.swing.JRadioButton();
        drawButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setBackground(J3DTheme.UI_SURFACE.color());
        setForeground(new java.awt.Color(51, 204, 0));
        setMaximumSize(new java.awt.Dimension(301, 261));
        setMinimumSize(new java.awt.Dimension(301, 261));

        jScrollPane2.setBackground(J3DTheme.UI_SURFACE.color());
        jScrollPane2.setMaximumSize(new java.awt.Dimension(279, 698));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(279, 16));

        jPanel1.setBackground(J3DTheme.UI_SURFACE.color());

        randomTriBtn.setBackground(J3DTheme.BACKGROUND.color());
        randomTriBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        randomTriBtn.setText("randomTri");
        randomTriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomTriBtnActionPerformed(evt);
            }
        });

        debugLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        debugLabel.setText("Debug");

        drawLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        drawLabel.setText("Draw");

        logTextArea.setBackground(J3DTheme.BACKGROUND.color());
        logTextArea.setColumns(20);
        logTextArea.setForeground(J3DTheme.TEXT_PRIMARY.color());
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        logLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        logLabel.setText("Logs");

        sliderYaw.setMaximum(180);
        sliderYaw.setMinimum(-180);
        sliderYaw.setValue(0);
        sliderYaw.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderYawStateChanged(evt);
            }
        });

        sliderPitch.setMaximum(180);
        sliderPitch.setMinimum(-180);
        sliderPitch.setValue(0);
        sliderPitch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPitchStateChanged(evt);
            }
        });

        sliderRoll.setMaximum(180);
        sliderRoll.setMinimum(-180);
        sliderRoll.setValue(0);
        sliderRoll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRollStateChanged(evt);
            }
        });

        camRotationLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        camRotationLabel1.setText("Cam Rotation");

        YawLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        YawLabel.setText("Yaw");

        PitchLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        PitchLabel.setText("Pitch");

        RollLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        RollLabel.setText("Roll");

        NoneRadioButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        NoneRadioButton.setSelected(true);
        NoneRadioButton.setText("None");
        NoneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel2.setText("Triangle Debugging Info");

        showTriDistCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        showTriDistCheckBox.setText("Show Triangle Distances");
        showTriDistCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriDistCheckBoxActionPerformed(evt);
            }
        });

        showTriDepthCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        showTriDepthCheckBox.setText("Show Triangle Depth Values");
        showTriDepthCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriDepthCheckBoxActionPerformed(evt);
            }
        });

        showTriNormalsCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        showTriNormalsCheckBox.setText("Show Triangle Normals");
        showTriNormalsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriNormalsCheckBoxActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(BucketSortRadio);
        BucketSortRadio.setForeground(J3DTheme.TEXT_PRIMARY.color());
        BucketSortRadio.setText("Bucket Sort");
        BucketSortRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BucketSortRadioActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(CamDistSortRadio);
        CamDistSortRadio.setForeground(J3DTheme.TEXT_PRIMARY.color());
        CamDistSortRadio.setText("CamDist Sort");
        CamDistSortRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamDistSortRadioActionPerformed(evt);
            }
        });

        jLabel1.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel1.setText("Triangle Sorting Algorithm");

        backFaceCullingCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        backFaceCullingCheckBox.setText("Back Face Culling");
        backFaceCullingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFaceCullingCheckBoxActionPerformed(evt);
            }
        });

        jLabel3.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel3.setText("General Toggles");

        sortMethodButtonGroup.add(visibleSortRadioButton);
        visibleSortRadioButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        visibleSortRadioButton.setText("Visible Sort");
        visibleSortRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleSortRadioButtonActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(camDepthSortRadioButton);
        camDepthSortRadioButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        camDepthSortRadioButton.setText("CamDepth Sort");
        camDepthSortRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camDepthSortRadioButtonActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(DDUUIDSortRadioButton);
        DDUUIDSortRadioButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        DDUUIDSortRadioButton.setSelected(true);
        DDUUIDSortRadioButton.setText("DDUUID");
        DDUUIDSortRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDUUIDSortRadioButtonActionPerformed(evt);
            }
        });

        drawButton.setBackground(J3DTheme.BACKGROUND.color());
        drawButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        drawButton.setText("draw");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(J3DTheme.BACKGROUND.color());
        clearButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camRotationLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sliderRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(sliderPitch, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(sliderYaw, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(backFaceCullingCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(visibleSortRadioButton)
                                    .addComponent(BucketSortRadio)
                                    .addComponent(CamDistSortRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DDUUIDSortRadioButton)
                                    .addComponent(camDepthSortRadioButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NoneRadioButton)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showTriDistCheckBox)
                                    .addComponent(showTriDepthCheckBox)
                                    .addComponent(showTriNormalsCheckBox))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PitchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(drawLabel)
                        .addGap(18, 18, 18)
                        .addComponent(drawButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(debugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomTriBtn))
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawLabel)
                    .addComponent(drawButton)
                    .addComponent(clearButton))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomTriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debugLabel))
                .addGap(18, 18, 18)
                .addComponent(logLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camRotationLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderYaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YawLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderPitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PitchLabel))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RollLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(NoneRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTriDistCheckBox)
                .addGap(5, 5, 5)
                .addComponent(showTriDepthCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTriNormalsCheckBox)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(CamDistSortRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibleSortRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camDepthSortRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DDUUIDSortRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BucketSortRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backFaceCullingCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NoneRadioButton.getAccessibleContext().setAccessibleName("jRadioButton1");

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DDUUIDSortRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDUUIDSortRadioButtonActionPerformed
        if (DDUUIDSortRadioButton.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.DDUUIDSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_DDUUIDSortRadioButtonActionPerformed

    private void camDepthSortRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camDepthSortRadioButtonActionPerformed
        if  (camDepthSortRadioButton.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.CAMDEPTHSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_camDepthSortRadioButtonActionPerformed

    private void visibleSortRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleSortRadioButtonActionPerformed
        if (visibleSortRadioButton.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.VISIBLESORT);
            frame.repaint();
        }
    }//GEN-LAST:event_visibleSortRadioButtonActionPerformed

    private void backFaceCullingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFaceCullingCheckBoxActionPerformed
        J3DSettings.setUseBackFaceCulling(backFaceCullingCheckBox.isSelected());
        frame.repaint();
    }//GEN-LAST:event_backFaceCullingCheckBoxActionPerformed

    private void CamDistSortRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamDistSortRadioActionPerformed
        if (CamDistSortRadio.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.CAMDISTSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_CamDistSortRadioActionPerformed

    private void BucketSortRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BucketSortRadioActionPerformed
        if (BucketSortRadio.isSelected()) {
            Static.getLog().println("Bucket Sort not implemented yet. Defaulting to CamDist Sort.");
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.CAMDISTSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_BucketSortRadioActionPerformed

    private void showTriNormalsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriNormalsCheckBoxActionPerformed
        if (showTriNormalsCheckBox.isSelected()) {
            J3DSettings.setShowNormals(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            J3DSettings.setShowNormals(false);
        }
        frame.repaint();
    }//GEN-LAST:event_showTriNormalsCheckBoxActionPerformed

    private void showTriDepthCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriDepthCheckBoxActionPerformed
        if  (showTriDepthCheckBox.isSelected()) {
            J3DSettings.setShowDepth(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            J3DSettings.setShowDepth(false);
        }
        frame.repaint();
    }//GEN-LAST:event_showTriDepthCheckBoxActionPerformed

    private void showTriDistCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriDistCheckBoxActionPerformed
        if (showTriDistCheckBox.isSelected()) {
            J3DSettings.setShowTriDistances(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            J3DSettings.setShowTriDistances(false);
        }
        frame.repaint();
    }//GEN-LAST:event_showTriDistCheckBoxActionPerformed

    private void NoneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneRadioButtonActionPerformed
        if (NoneRadioButton.isSelected()) {
            J3DSettings.setShowTriDistances(false);
            J3DSettings.setShowDepth(false);
            J3DSettings.setShowNormals(false);
            if (showTriDistCheckBox.isSelected()) showTriDistCheckBox.doClick();
            if (showTriDepthCheckBox.isSelected()) showTriDepthCheckBox.doClick();
            if (showTriNormalsCheckBox.isSelected()) showTriNormalsCheckBox.doClick();
            frame.repaint();
        }
    }//GEN-LAST:event_NoneRadioButtonActionPerformed

    private void sliderRollStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRollStateChanged
        int value = sliderRoll.getValue();
        Static.camera.getRotation().setRoll(value);
        frame.repaint();
    }//GEN-LAST:event_sliderRollStateChanged

    private void sliderPitchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPitchStateChanged
        int value = sliderPitch.getValue();
        Static.camera.getRotation().setPitch(value);
        frame.repaint();
    }//GEN-LAST:event_sliderPitchStateChanged

    private void sliderYawStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderYawStateChanged
        int value = sliderYaw.getValue();
        Static.camera.getRotation().setYaw(value);
        frame.repaint();
    }//GEN-LAST:event_sliderYawStateChanged

    private void randomTriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomTriBtnActionPerformed
        Random random = new Random();
        int red = random.nextInt(256);   // 0 to 255
        int green = random.nextInt(256);
        int blue = random.nextInt(256);
        //
        Color randomColor = new Color(red, green, blue);

        Vector3 lowerBound = new Vector3(-10 , -10, -10);
        Vector3 upperBound = new Vector3(10 , 10, 10);

        GPoint[] gps = new GPoint[]{
            new GPoint(Vector3.random(lowerBound, upperBound)),
            new GPoint(Vector3.random(lowerBound, upperBound)),
            new GPoint(Vector3.random(lowerBound, upperBound))
        };

        GTri t = new GTri(randomColor,
            gps[0], gps[1], gps[2]
        );

        Thing g = new Thing(sceneManager, null, "Random Tri").addObjs(t, gps[0], gps[1], gps[2]);

        Static.getLog().println("Added random tri " + t.getId() + " to layer " + g);
        frame.repaint();
    }//GEN-LAST:event_randomTriBtnActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        frame.repaint();
    }//GEN-LAST:event_drawButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        sceneManager.layers.forEach(frame -> {
            if (!frame.getIdentifier().equals(Layer.BACKGROUND_ID)) frame.clear();
        });
        frame.repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    public void run(SceneManager r, Executor e, Frame f) {
        sceneManager = r;
        executor = e;
        frame = f;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton BucketSortRadio;
    public javax.swing.JRadioButton CamDistSortRadio;
    public javax.swing.JRadioButton DDUUIDSortRadioButton;
    public javax.swing.JRadioButton NoneRadioButton;
    public javax.swing.JLabel PitchLabel;
    public javax.swing.JLabel RollLabel;
    public javax.swing.JLabel YawLabel;
    public javax.swing.JCheckBox backFaceCullingCheckBox;
    public javax.swing.JRadioButton camDepthSortRadioButton;
    public javax.swing.JLabel camRotationLabel1;
    public javax.swing.JButton clearButton;
    public javax.swing.JLabel debugLabel;
    public javax.swing.JButton drawButton;
    public javax.swing.JLabel drawLabel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel logLabel;
    public javax.swing.JTextArea logTextArea;
    public javax.swing.JButton randomTriBtn;
    public javax.swing.JCheckBox showTriDepthCheckBox;
    public javax.swing.JCheckBox showTriDistCheckBox;
    public javax.swing.JCheckBox showTriNormalsCheckBox;
    public javax.swing.JSlider sliderPitch;
    public javax.swing.JSlider sliderRoll;
    public javax.swing.JSlider sliderYaw;
    private javax.swing.ButtonGroup sortMethodButtonGroup;
    public javax.swing.JRadioButton visibleSortRadioButton;
    // End of variables declaration//GEN-END:variables
}
