/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d.ui.engine.floating;

import com.j3d.StaticRefs;
import com.j3d.engine.scene.nodes.layer.Layer;
import com.j3d.engine.scene.nodes.geometry.GPoint;
import com.j3d.engine.scene.nodes.geometry.GTri;
import com.j3d.engine.scene.nodes.Thing;
import com.j3d.engine.math.matrix.Vector3;
import com.j3d.StaticConfig;
import com.j3d.threads.StatisticsThread;
import com.j3d.ui.theme.J3DScrollBarUI;
import com.j3d.ui.theme.J3DTheme;
import com.j3d.ui.dialog.AreYouSure;
import com.j3d.ui.engine.FloatingPanel;
import com.j3d.utility.generators.JLabelRichText;

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.UUID;
import java.util.function.Consumer;

import static com.j3d.StaticRefs.*;

/**
 *
 * @author ACER
 */
public class DebugPanel extends javax.swing.JPanel {

    public FloatingPanel floatingPanel = new FloatingPanel("Debug Panel");
    private final Map<UUID, JLabel> statsLabelMap = new HashMap<>();
    private final StatisticsThread statisticsThread = new StatisticsThread(
            (map) -> {
                JLabelRichText style = new JLabelRichText().bold().italic().font(Color.RED, "4");
                statsLabelMap.forEach(
                        (uuid, label) -> label.setText(
                               JLabelRichText.from(map.get(uuid).toString(), style).wrapHTML()
                        )
                );
            }
    );

    /**
     * Creates new form NewJPanel
     */
    public DebugPanel() {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this); // 'this' refers to the panel
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        floatingPanel.finish(this, (c) -> {});
        J3DScrollBarUI.setBars(jScrollPane1);
        J3DScrollBarUI.setBars(jScrollPane2);
        J3DTheme.commitAsGenericLbl(logLabel, false);
        J3DTheme.commitAsGenericLbl(debugLabel, false);
        J3DTheme.commitAsGenericLbl(randomTriBtn, true);
        J3DTheme.commitAsGenericLbl(NoneRadioButton, true);
        J3DTheme.commitAsGenericLbl(jLabel2, false);
        J3DTheme.commitAsGenericLbl(showTriDistCheckBox, true);
        J3DTheme.commitAsGenericLbl(showTriDepthCheckBox, true);
        J3DTheme.commitAsGenericLbl(showTriNormalsCheckBox, true);
        J3DTheme.commitAsGenericLbl(drawButton, true);
        J3DTheme.commitAsGenericLbl(clearButton, true);
        J3DTheme.commitAsGenericUi(jPanel1);
        J3DTheme.commitAsGenericUi(jScrollPane2);
        J3DTheme.commitAsGenericUi(jScrollPane1);
        J3DTheme.commitAsGenericLbl(logTextArea, true);
        J3DTheme.commitAsGenericLbl(repaintsPerSecondLabel, true);
        J3DTheme.commitAsGenericLbl(jLabel4, false);
        J3DTheme.commitAsGenericLbl(jLabel5, false);
        J3DTheme.commitAsGenericLbl(jLabel6, false);
        J3DTheme.commitAsGenericLbl(trianglesInSceneLabel, false);
        J3DTheme.commitAsGenericUi(this);

    }

    public void toggleHidden() {
        floatingPanel.toggleHidden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortMethodButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        randomTriBtn = new javax.swing.JButton();
        debugLabel = new javax.swing.JLabel();
        NoneRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        showTriDistCheckBox = new javax.swing.JCheckBox();
        showTriDepthCheckBox = new javax.swing.JCheckBox();
        showTriNormalsCheckBox = new javax.swing.JCheckBox();
        drawButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        logLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        repaintsPerSecondLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        trianglesInSceneLabel = new javax.swing.JLabel();

        setBackground(J3DTheme.UI_SURFACE.color());
        setForeground(new java.awt.Color(51, 204, 0));
        setMaximumSize(new java.awt.Dimension(301, 261));
        setMinimumSize(new java.awt.Dimension(301, 261));

        jScrollPane2.setBackground(J3DTheme.UI_SURFACE.color());
        jScrollPane2.setMaximumSize(new java.awt.Dimension(279, 698));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(279, 16));

        jPanel1.setBackground(J3DTheme.UI_SURFACE.color());

        randomTriBtn.setBackground(J3DTheme.BACKGROUND.color());
        randomTriBtn.setForeground(J3DTheme.TEXT_PRIMARY.color());
        randomTriBtn.setText("randomTri");
        randomTriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomTriBtnActionPerformed(evt);
            }
        });

        debugLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        debugLabel.setText("Debug");

        NoneRadioButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        NoneRadioButton.setSelected(true);
        NoneRadioButton.setText("None");
        NoneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel2.setText("Triangle Debugging Info");

        showTriDistCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        showTriDistCheckBox.setText("Show Triangle Distances");
        showTriDistCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriDistCheckBoxActionPerformed(evt);
            }
        });

        showTriDepthCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        showTriDepthCheckBox.setText("Show Triangle Depth Values");
        showTriDepthCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriDepthCheckBoxActionPerformed(evt);
            }
        });

        showTriNormalsCheckBox.setForeground(J3DTheme.TEXT_PRIMARY.color());
        showTriNormalsCheckBox.setText("Show Triangle Normals");
        showTriNormalsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriNormalsCheckBoxActionPerformed(evt);
            }
        });

        drawButton.setBackground(J3DTheme.BACKGROUND.color());
        drawButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        drawButton.setText("force swing repaint");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(J3DTheme.BACKGROUND.color());
        clearButton.setForeground(J3DTheme.TEXT_PRIMARY.color());
        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(drawButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(debugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(randomTriBtn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NoneRadioButton)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showTriDistCheckBox)
                        .addComponent(showTriDepthCheckBox)
                        .addComponent(showTriNormalsCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawButton)
                    .addComponent(clearButton))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomTriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debugLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(NoneRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTriDistCheckBox)
                .addGap(5, 5, 5)
                .addComponent(showTriDepthCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTriNormalsCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NoneRadioButton.getAccessibleContext().setAccessibleName("jRadioButton1");

        jScrollPane2.setViewportView(jPanel1);

        logLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        logLabel.setText("Logs");

        logTextArea.setBackground(J3DTheme.BACKGROUND.color());
        logTextArea.setColumns(20);
        logTextArea.setForeground(J3DTheme.TEXT_PRIMARY.color());
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        jLabel4.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel4.setText("Repaints:");

        repaintsPerSecondLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        repaintsPerSecondLabel.setText("jLabel5");

        jLabel6.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel6.setText("per second");

        jLabel5.setForeground(J3DTheme.TEXT_PRIMARY.color());
        jLabel5.setText("Triangles:");

        trianglesInSceneLabel.setForeground(J3DTheme.TEXT_PRIMARY.color());
        trianglesInSceneLabel.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trianglesInSceneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(repaintsPerSecondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(repaintsPerSecondLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(trianglesInSceneLabel))
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showTriNormalsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriNormalsCheckBoxActionPerformed
        if (showTriNormalsCheckBox.isSelected()) {
            StaticConfig.setShowNormals(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            StaticConfig.setShowNormals(false);
        }
        StaticRefs.getMainPanel().repaint();
    }//GEN-LAST:event_showTriNormalsCheckBoxActionPerformed

    private void showTriDepthCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriDepthCheckBoxActionPerformed
        if  (showTriDepthCheckBox.isSelected()) {
            StaticConfig.setShowDepth(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            StaticConfig.setShowDepth(false);
        }
        StaticRefs.getMainPanel().repaint();
    }//GEN-LAST:event_showTriDepthCheckBoxActionPerformed

    private void showTriDistCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriDistCheckBoxActionPerformed
        if (showTriDistCheckBox.isSelected()) {
            StaticConfig.setShowTriDistances(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            StaticConfig.setShowTriDistances(false);
        }
    }//GEN-LAST:event_showTriDistCheckBoxActionPerformed

    private void NoneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneRadioButtonActionPerformed
        if (NoneRadioButton.isSelected()) {
            StaticConfig.setShowTriDistances(false);
            StaticConfig.setShowDepth(false);
            StaticConfig.setShowNormals(false);
            if (showTriDistCheckBox.isSelected()) showTriDistCheckBox.doClick();
            if (showTriDepthCheckBox.isSelected()) showTriDepthCheckBox.doClick();
            if (showTriNormalsCheckBox.isSelected()) showTriNormalsCheckBox.doClick();
        }
        StaticRefs.getMainPanel().repaint();
    }//GEN-LAST:event_NoneRadioButtonActionPerformed

    private void randomTriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomTriBtnActionPerformed
        Random random = new Random();
        int red = random.nextInt(256);   // 0 to 255
        int green = random.nextInt(256);
        int blue = random.nextInt(256);
        //
        Color randomColor = new Color(red, green, blue);

        Vector3 lowerBound = new Vector3(-10 , -10, -10);
        Vector3 upperBound = new Vector3(10 , 10, 10);

        GPoint[] gps = new GPoint[]{
            new GPoint(Vector3.random(lowerBound, upperBound)),
            new GPoint(Vector3.random(lowerBound, upperBound)),
            new GPoint(Vector3.random(lowerBound, upperBound))
        };

        GTri t = new GTri(randomColor,
            gps[0], gps[1], gps[2]
        );

        Thing g = new Thing(
                null,
                "Random Tri " + t.getId().toString().substring(0, 4)).addObjs(
                        t, gps[0], gps[1], gps[2],
                // the fix
                t.getLegA(), t.getLegB(), t.getLegC()
        );

        StaticRefs.getLog().println("Added random tri " + t.getId() + " to layer " + g);

        StaticRefs.getMainPanel().repaint();
    }//GEN-LAST:event_randomTriBtnActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        StaticRefs.getMainPanel().repaint();
    }//GEN-LAST:event_drawButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        AreYouSure ays = new AreYouSure(getMainFrame(), true, "This will clear all layers.");
        ays.setVisible(true);
        if (!ays.canProceed()) return;
        getSceneManager().layers.forEach(frame -> {
            if (!frame.getName().equals(Layer.BACKGROUND_ID)) frame.clear();
        });
        StaticRefs.getMainPanel().repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    public void startStatisticsThread() {
        statsLabelMap.put(StatisticsThread.IdEnum.REPAINTS_PER_SECOND.getId(), repaintsPerSecondLabel);
        statisticsThread.registerStatistic(StatisticsThread.IdEnum.REPAINTS_PER_SECOND.getId());
        StaticRefs.getMainPanel().registerRunnable(
                () -> statisticsThread.increment(StatisticsThread.IdEnum.REPAINTS_PER_SECOND.getId())
        );
        statisticsThread.execute();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton NoneRadioButton;
    public javax.swing.JButton clearButton;
    public javax.swing.JLabel debugLabel;
    public javax.swing.JButton drawButton;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel logLabel;
    public javax.swing.JTextArea logTextArea;
    public javax.swing.JButton randomTriBtn;
    private javax.swing.JLabel repaintsPerSecondLabel;
    public javax.swing.JCheckBox showTriDepthCheckBox;
    public javax.swing.JCheckBox showTriDistCheckBox;
    public javax.swing.JCheckBox showTriNormalsCheckBox;
    private javax.swing.ButtonGroup sortMethodButtonGroup;
    private javax.swing.JLabel trianglesInSceneLabel;
    // End of variables declaration//GEN-END:variables
}
