package com.j3d.engine.draw.methods;

import com.j3d.engine.draw.SortMethod;
import com.j3d.engine.draw.TriListener;
import com.j3d.engine.draw.methods.utils.ZDepthIdBuffer;
import com.j3d.engine.geometry.geo2d.GTri;

import java.util.*;
import java.util.stream.Collectors;

/**
 * The following sort method was generated by GitHub Copilot Chat (IntelliJ plugin) on 03-01-2026 with the following prompt:
 * <p>
 *     This is SortMethod and there is TriListener and GTri
 *     following the JDoc in Sortmethod make a class which will
 *     effeicntly sort the triangles such that only visible triangles
 *     will be rendered. keep in mind it has to strictly adhere to Sortmethod
 *     JDoc and also dont use back face culling as i'll implement that myself.
 * </p>
 * <p>
 * VisibleSort is a SortMethod that keeps only triangles which are visible
 * according to a software Z-buffer pass performed with ZDepthIdBuffer.
 * </p>
 *
 * Behaviour requirements from SortMethod.javadoc:
 * - When a triangle is added via add(Object) it sorts the list according to its algorithm.
 * - clear() re-adds non-dirty triangles from the registered listeners.
 *
 * This implementation does NOT perform back-face culling (left for caller).
 */
public class VisibleSort extends SortMethod {

    public VisibleSort(ArrayList<TriListener> registered) {
        super(registered);
    }

    @Override
    public boolean add(GTri gTri) {
        if (this.contains(gTri)) {
            updateVisibilityAndSort();
            return false;
        }
        boolean changed = super.add(gTri);
        updateVisibilityAndSort();
        return changed;
    }

    @Override
    public void clear() {
        super.clear();
        // Re-add all non-dirty triangles from registered listeners as suggested by SortMethod javadoc
        registered.stream().filter(
                triListener -> !triListener.isDirty()
        ).forEach(
                listener -> this.add(listener.tri)
        );
    }

    /**
     * Performs a Z-buffer rasterization of all registered triangles and keeps only
     * those which appear on the final buffer (i.e. are visible). The remaining
     * visible triangles are sorted by depth (farthest first) to be suitable for
     * painter-style rendering if desired.
     */
    private void updateVisibilityAndSort() {
        // Lazy reference to avoid a hard dependency in the class header
        ZDepthIdBuffer zb = new ZDepthIdBuffer();
        zb.clear();

        // Rasterize all triangles known to the registered listeners
        for (TriListener tl : registered) {
            if (tl == null || tl.tri == null) continue;
            try {
                zb.tri(tl.tri);
            } catch (Throwable ignored) {
                // Defensive: don't let one bad triangle stop visibility determination
            }
        }

        // Collect visible UUIDs from the buffer
        UUID[][] buf = zb.getBuffer();
        Set<UUID> visibleIds = new HashSet<>();
        for (UUID[] row : buf) {
            for (UUID id : row) {
                if (id != null) visibleIds.add(id);
            }
        }

        // Build the visible triangle list in a deterministic way and sort by depth
        List<GTri> visibleTris = registered.stream()
                .filter(l -> l != null && l.tri != null && visibleIds.contains(l.tri.getId()))
                .map(l -> l.tri)
                .collect(Collectors.toList());

        visibleTris.sort((tri1, tri2) -> {
            double dist1 = tri1.calcDepth();
            double dist2 = tri2.calcDepth();
            if (Double.compare(dist1, dist2) == 0) {
                double euclid1 = tri1.euclideanDist();
                double euclid2 = tri2.euclideanDist();
                if (Double.compare(euclid1, euclid2) == 0) {
                    return tri1.getId().compareTo(tri2.getId());
                }
                return Double.compare(euclid2, euclid1); // farthest first
            }
            return Double.compare(dist2, dist1); // farthest first
        });

        // Replace current contents with the filtered & sorted visible triangles
        super.clear();
        super.addAll(visibleTris);
    }
}

