/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.j3d;

import com.j3d.engine.Layer;
import com.j3d.engine.Renderer;
import com.j3d.engine.draw.TriangleSortMethod;
import com.j3d.engine.geometry.geo2d.GPoint;
import com.j3d.engine.geometry.geo2d.GTri;
import com.j3d.engine.geometry.geo3d.Thing;
import com.j3d.engine.geometry.geo3d.Vector3;

import javax.swing.*;
import java.awt.*;
import java.util.Random;

/**
 *
 * @author ACER
 */
public class DebugPanel extends javax.swing.JPanel {

    public Executor executor = null;
    public Renderer renderer = null;
    public Frame frame = null;


    /**
     * Creates new form NewJPanel
     */
    public DebugPanel() {
        initComponents();
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this); // 'this' refers to the panel
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortMethodButtonGroup = new javax.swing.ButtonGroup();
        sliderYaw = new javax.swing.JSlider();
        sliderPitch = new javax.swing.JSlider();
        sliderRoll = new javax.swing.JSlider();
        camRotationLabel1 = new javax.swing.JLabel();
        YawLabel = new javax.swing.JLabel();
        PitchLabel = new javax.swing.JLabel();
        RollLabel = new javax.swing.JLabel();
        randomTriBtn = new javax.swing.JButton();
        debugLabel = new javax.swing.JLabel();
        drawLabel = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        NoneRadioButton = new javax.swing.JRadioButton();
        BucketSortRadio = new javax.swing.JRadioButton();
        CamDistSortRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backFaceCullingCheckBox = new javax.swing.JCheckBox();
        showTriDistCheckBox = new javax.swing.JCheckBox();
        showTriDepthCheckBox = new javax.swing.JCheckBox();
        showTriNormalsCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        visibleSortRadioButton = new javax.swing.JRadioButton();
        camDepthSortRadioButton = new javax.swing.JRadioButton();
        DDUUIDSortRadioButton = new javax.swing.JRadioButton();
        drawButton = new javax.swing.JToggleButton();
        clearButton = new javax.swing.JToggleButton();

        sliderYaw.setMaximum(180);
        sliderYaw.setMinimum(-180);
        sliderYaw.setValue(0);
        sliderYaw.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderYawStateChanged(evt);
            }
        });

        sliderPitch.setMaximum(180);
        sliderPitch.setMinimum(-180);
        sliderPitch.setValue(0);
        sliderPitch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPitchStateChanged(evt);
            }
        });

        sliderRoll.setMaximum(180);
        sliderRoll.setMinimum(-180);
        sliderRoll.setValue(0);
        sliderRoll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRollStateChanged(evt);
            }
        });

        camRotationLabel1.setText("Cam Rotation");

        YawLabel.setText("Yaw");

        PitchLabel.setText("Pitch");

        RollLabel.setText("Roll");

        randomTriBtn.setText("randomTri");
        randomTriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomTriBtnActionPerformed(evt);
            }
        });

        debugLabel.setText("Debug");

        drawLabel.setText("Draw");

        logLabel.setText("Logs");

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        NoneRadioButton.setSelected(true);
        NoneRadioButton.setText("None");
        NoneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneRadioButtonActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(BucketSortRadio);
        BucketSortRadio.setText("Bucket Sort");
        BucketSortRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BucketSortRadioActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(CamDistSortRadio);
        CamDistSortRadio.setText("CamDist Sort");
        CamDistSortRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamDistSortRadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Triangle Sorting Algorithm");

        jLabel2.setText("Triangle Debugging Info");

        backFaceCullingCheckBox.setText("Back Face Culling");
        backFaceCullingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFaceCullingCheckBoxActionPerformed(evt);
            }
        });

        showTriDistCheckBox.setText("Show Triangle Distances");
        showTriDistCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriDistCheckBoxActionPerformed(evt);
            }
        });

        showTriDepthCheckBox.setText("Show Triangle Depth Values");
        showTriDepthCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriDepthCheckBoxActionPerformed(evt);
            }
        });

        showTriNormalsCheckBox.setText("Show Triangle Normals");
        showTriNormalsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTriNormalsCheckBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("General Toggles");

        sortMethodButtonGroup.add(visibleSortRadioButton);
        visibleSortRadioButton.setText("Visible Sort");
        visibleSortRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleSortRadioButtonActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(camDepthSortRadioButton);
        camDepthSortRadioButton.setText("CamDepth Sort");
        camDepthSortRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camDepthSortRadioButtonActionPerformed(evt);
            }
        });

        sortMethodButtonGroup.add(DDUUIDSortRadioButton);
        DDUUIDSortRadioButton.setSelected(true);
        DDUUIDSortRadioButton.setText("DDUUID");
        DDUUIDSortRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDUUIDSortRadioButtonActionPerformed(evt);
            }
        });

        drawButton.setText("draw");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                draw(evt);
            }
        });

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drawLabel)
                        .addGap(32, 32, 32)
                        .addComponent(drawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camRotationLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sliderRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(sliderPitch, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(sliderYaw, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PitchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(debugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomTriBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NoneRadioButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showTriDistCheckBox)
                    .addComponent(showTriDepthCheckBox)
                    .addComponent(showTriNormalsCheckBox)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backFaceCullingCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibleSortRadioButton)
                    .addComponent(BucketSortRadio)
                    .addComponent(CamDistSortRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DDUUIDSortRadioButton)
                    .addComponent(camDepthSortRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoneRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTriDistCheckBox)
                        .addGap(5, 5, 5)
                        .addComponent(showTriDepthCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTriNormalsCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(CamDistSortRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visibleSortRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(camDepthSortRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DDUUIDSortRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BucketSortRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backFaceCullingCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drawLabel)
                            .addComponent(drawButton)
                            .addComponent(clearButton))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(randomTriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(debugLabel))
                        .addGap(18, 18, 18)
                        .addComponent(logLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(camRotationLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sliderYaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YawLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sliderPitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PitchLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sliderRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RollLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        NoneRadioButton.getAccessibleContext().setAccessibleName("jRadioButton1");
    }// </editor-fold>//GEN-END:initComponents

    private void sliderYawStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderYawStateChanged
        int value = sliderYaw.getValue();
        Main.camera.getRotation().setYaw(value);
        frame.repaint();
    }//GEN-LAST:event_sliderYawStateChanged

    private void sliderPitchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPitchStateChanged
        int value = sliderPitch.getValue();
        Main.camera.getRotation().setPitch(value);
        frame.repaint();
    }//GEN-LAST:event_sliderPitchStateChanged

    private void sliderRollStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRollStateChanged
        int value = sliderRoll.getValue();
        Main.camera.getRotation().setRoll(value);
        frame.repaint();
    }//GEN-LAST:event_sliderRollStateChanged

    private void randomTriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomTriBtnActionPerformed
        Random random = new Random();
        int red = random.nextInt(256);   // 0 to 255
        int green = random.nextInt(256);
        int blue = random.nextInt(256);
        //
        Color randomColor = new Color(red, green, blue);

        Vector3 lowerBound = new Vector3(-10 , -10, -10);
        Vector3 upperBound = new Vector3(10 , 10, 10);

        GPoint[] gps = new GPoint[]{
            new GPoint(Vector3.random(lowerBound, upperBound)),
            new GPoint(Vector3.random(lowerBound, upperBound)),
            new GPoint(Vector3.random(lowerBound, upperBound))
        };

        GTri t = new GTri(randomColor,
            gps[0], gps[1], gps[2]
        );

        Thing g = new Thing(renderer, null, "Random Tri").addObjs(t, gps[0], gps[1], gps[2]);

        J3DSettings.log.println("Added random tri " + t.getId() + " to layer " + g);
        frame.repaint();

    }//GEN-LAST:event_randomTriBtnActionPerformed

    private void NoneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneRadioButtonActionPerformed
        if (NoneRadioButton.isSelected()) {
            J3DSettings.setShowTriDistances(false);
            J3DSettings.setShowDepth(false);
            J3DSettings.setShowNormals(false);
            if (showTriDistCheckBox.isSelected()) showTriDistCheckBox.doClick();
            if (showTriDepthCheckBox.isSelected()) showTriDepthCheckBox.doClick();
            if (showTriNormalsCheckBox.isSelected()) showTriNormalsCheckBox.doClick();
            frame.repaint();
        }
    }//GEN-LAST:event_NoneRadioButtonActionPerformed

    private void backFaceCullingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFaceCullingCheckBoxActionPerformed
        J3DSettings.setUseBackFaceCulling(backFaceCullingCheckBox.isSelected());
        frame.repaint();
    }//GEN-LAST:event_backFaceCullingCheckBoxActionPerformed

    private void showTriDistCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriDistCheckBoxActionPerformed
        if (showTriDistCheckBox.isSelected()) {
            J3DSettings.setShowTriDistances(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            J3DSettings.setShowTriDistances(false);
        }
        frame.repaint();
    }//GEN-LAST:event_showTriDistCheckBoxActionPerformed

    private void showTriDepthCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriDepthCheckBoxActionPerformed
        if  (showTriDepthCheckBox.isSelected()) {
            J3DSettings.setShowDepth(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            J3DSettings.setShowDepth(false);
        }
        frame.repaint();
    }//GEN-LAST:event_showTriDepthCheckBoxActionPerformed

    private void showTriNormalsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTriNormalsCheckBoxActionPerformed
        if (showTriNormalsCheckBox.isSelected()) {
            J3DSettings.setShowNormals(true);
            if (NoneRadioButton.isSelected()) NoneRadioButton.doClick(); // unselect none
        } else {
            J3DSettings.setShowNormals(false);
        }
        frame.repaint();
    }//GEN-LAST:event_showTriNormalsCheckBoxActionPerformed

    private void BucketSortRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BucketSortRadioActionPerformed
        if (BucketSortRadio.isSelected()) {
            J3DSettings.log.println("Bucket Sort not implemented yet. Defaulting to CamDist Sort.");
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.CAMDISTSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_BucketSortRadioActionPerformed

    private void visibleSortRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleSortRadioButtonActionPerformed
        if (visibleSortRadioButton.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.VISIBLESORT);
            frame.repaint();
        }
    }//GEN-LAST:event_visibleSortRadioButtonActionPerformed

    private void CamDistSortRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamDistSortRadioActionPerformed
        if (CamDistSortRadio.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.CAMDISTSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_CamDistSortRadioActionPerformed

    private void DDUUIDSortRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDUUIDSortRadioButtonActionPerformed
        if (DDUUIDSortRadioButton.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.DDUUIDSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_DDUUIDSortRadioButtonActionPerformed

    private void camDepthSortRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camDepthSortRadioButtonActionPerformed
        if  (camDepthSortRadioButton.isSelected()) {
            J3DSettings.setTriangleSortMethod(TriangleSortMethod.CAMDEPTHSORT);
            frame.repaint();
        }
    }//GEN-LAST:event_camDepthSortRadioButtonActionPerformed

    private void draw(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_draw

        frame.repaint();
    }//GEN-LAST:event_draw

    private void clear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear
        renderer.layers.forEach(frame -> {
            if (!frame.getIdentifier().equals(Layer.backgroundId)) frame.clear();
        });
        frame.repaint();
    }//GEN-LAST:event_clear

    public void run(Renderer r, Executor e, Frame f) {
        renderer = r;
        executor = e;
        frame = f;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BucketSortRadio;
    private javax.swing.JRadioButton CamDistSortRadio;
    private javax.swing.JRadioButton DDUUIDSortRadioButton;
    private javax.swing.JRadioButton NoneRadioButton;
    private javax.swing.JLabel PitchLabel;
    private javax.swing.JLabel RollLabel;
    private javax.swing.JLabel YawLabel;
    private javax.swing.JCheckBox backFaceCullingCheckBox;
    private javax.swing.JRadioButton camDepthSortRadioButton;
    private javax.swing.JLabel camRotationLabel1;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JLabel debugLabel;
    private javax.swing.JToggleButton drawButton;
    private javax.swing.JLabel drawLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logLabel;
    public javax.swing.JTextArea logTextArea;
    private javax.swing.JButton randomTriBtn;
    private javax.swing.JCheckBox showTriDepthCheckBox;
    private javax.swing.JCheckBox showTriDistCheckBox;
    private javax.swing.JCheckBox showTriNormalsCheckBox;
    private javax.swing.JSlider sliderPitch;
    private javax.swing.JSlider sliderRoll;
    private javax.swing.JSlider sliderYaw;
    private javax.swing.ButtonGroup sortMethodButtonGroup;
    private javax.swing.JRadioButton visibleSortRadioButton;
    // End of variables declaration//GEN-END:variables
}
