/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d;

import com.j3d.engine.Logger;
import com.j3d.engine.Renderer;
import com.j3d.engine.geometry.ScreenPoint;
import com.j3d.engine.geometry.geo3d.Camera;
import com.j3d.engine.geometry.geo3d.Rotation;
import com.j3d.engine.geometry.geo3d.Vector3;
import com.j3d.engine.interact.cmd.CommandPallete;
import com.j3d.engine.interact.cmd.CommandParser;
import com.j3d.engine.interact.input.mouse.MOwner;
import com.j3d.engine.interact.input.mouse.MouseOwner;
import com.j3d.engine.interact.input.mouse.NoMouseOwner;
import com.j3d.engine.interact.selection.SelectionManager;
import com.j3d.jaiva.Testing;
import com.j3d.ui.Cursors;
import com.j3d.ui.tb.Toolbox;
import com.jaiva.JBundler;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author ACER
 */
public class Main extends javax.swing.JFrame {
    public static JBundler jBundler = null;
    public static Renderer renderer = null;
    public static Executor executor = null;
    public static boolean run = true;
    public static JFrame f = null;
    public static Camera camera = new Camera()
            .setPosition(new Vector3(20, 20, -20))
            .setRotation(new Rotation(0, 0, 0))
            .setProjectionPlane(new Vector3(0, 0, 50));
    public static DebugPanel dp = new DebugPanel();
    private static MOwner mouseOwner = MOwner.SELECTION;
    public static ScreenPoint mousePos = null;
    public static ScreenPoint[] selectionArea = new ScreenPoint[2];
    private static CommandPallete commandPallete = new CommandPallete();
    public static CommandParser commandParser;

    public static void setMouseOwner(MOwner owner) {
        mouseOwner = owner;
    }
    public static MOwner getMouseOwner() {
        return mouseOwner;
    }

    /**
     * Creates new form Main2
     */
    public Main() {
        ArrayList<MouseOwner> owners = new ArrayList<>();
        owners.add(SelectionManager.selectionMouseOwner);
        owners.add(new NoMouseOwner());

        owners.forEach(this::addMouseListener);
        owners.forEach(this::addMouseMotionListener);
        initComponents();
    }

    /**
     * Initializes (if not already initialized) the Jaiva Instance by inputting the input file and passing {@link Testing} class
     * @param g The graphics
     * @param r The Renderer Instance.
     */
    private void initBundler(Graphics g, Renderer r) {
        if (jBundler == null) {
            try {
                jBundler = new JBundler("C:\\Users\\ACER\\Documents\\code\\Jaiva3dEngine\\src\\main\\resources\\file.jiv", Testing.class);
                jBundler.run(r);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }


    /**
     * Repaints the debug panel, command pallete, and main frame on the Event Dispatch Thread.
     * This should only be called from non-EDT threads. e.g. from the Renderer thread.
     */
    public static void repaintL() {
        SwingUtilities.invokeLater(() -> {
            if (dp != null) {
                dp.revalidate();
                dp.repaint();
            }
            if (commandPallete != null) {
                commandPallete.revalidate();
                commandPallete.repaint();
            }
            if (f != null) {
                f.revalidate();
                f.repaint();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new J3DPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J3D");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1489, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1503, 857));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException e) {
            throw new RuntimeException(e);
        }
        f = new Main();
        f.setExtendedState(JFrame.MAXIMIZED_BOTH);
        renderer = new Renderer(J3DSettings.screenSize);
        executor = new Executor(renderer);
        dp.run(renderer, executor, f);
        JLayeredPane layeredPane = f.getLayeredPane();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setSize(J3DSettings.screenSize.width, J3DSettings.screenSize.height);
        f.setResizable(false);

        mainPanel.setFocusable(true);

        InputMap im = mainPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = mainPanel.getActionMap();
        new KeyBindings(im, am, commandPallete);

        Toolbox toolbox = new Toolbox();
        // Toolbox at the top and extends full width but not very tall
        toolbox.setBounds(0, 0, J3DSettings.screenSize.width - 50, toolbox.getPreferredSize().height);
        
        // add menubar to layered pane
        JMenuBar mb = f.getJMenuBar();
        if (mb != null) {
            layeredPane.add(mb, JLayeredPane.POPUP_LAYER);
        }
        layeredPane.add(toolbox, JLayeredPane.MODAL_LAYER); // above default layer

        mainPanel.requestFocusInWindow();
        mainPanel.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        mainPanel.setBounds(0, 0, J3DSettings.screenSize.width, J3DSettings.screenSize.height);
        mainPanel.setPreferredSize(new Dimension(J3DSettings.screenSize.width, J3DSettings.screenSize.height));
//        layeredPane.add(mainPanel, JLayeredPane.DEFAULT_LAYER);

        dp.setBounds(20, toolbox.getPreferredSize().height + 40, dp.getPreferredSize().width, dp.getPreferredSize().height); // small corner overlay
        dp.setOpaque(true);
        dp.setBackground(Color.WHITE);
        dp.setVisible(false);
        J3DSettings.log = new Logger(dp.logTextArea); // initialize logger with the text area
        layeredPane.add(dp, JLayeredPane.PALETTE_LAYER);
        
        Rectangle bounds = f.getBounds();
        Dimension size = commandPallete.getPreferredSize();
        int x = ((bounds.width - size.width) / 2) - 60;
        int y = bounds.height - size.height - 200;
        commandPallete.setBounds(x, y, size.width, size.height);

        commandPallete.setOpaque(true);
        commandPallete.setBackground(new Color(30, 30, 30, 8));
        commandPallete.setVisible(true);
        layeredPane.add(commandPallete, JLayeredPane.POPUP_LAYER);

        commandParser = new CommandParser(commandPallete);

        mainPanel.getRootPane().setFocusable(true);
        mainPanel.getRootPane().requestFocusInWindow();

//        frame.add(new Main());
//        f.setVisible(true);

        Cursors.init(f);
        Cursors.setDefault();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
