/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d;

import com.j3d.engine.Layer;
import com.j3d.engine.Renderer;
import com.j3d.engine.geometry.GLine;
import com.j3d.engine.geometry.GObject;
import com.j3d.engine.geometry.GPoint;
import com.j3d.engine.geometry.GTri;
import com.j3d.engine.geometry.base.CartesianPoint;

import java.awt.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author ACER
 */
public class NewJFrame extends javax.swing.JFrame {
    
    public static Executor executor = null;
    public static Renderer renderer = null;
    public static Frame frame = null;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawButton = new java.awt.Button();
        clearButton = new java.awt.Button();
        randomTriBtn = new javax.swing.JButton();
        debugLabel = new javax.swing.JLabel();
        drawLabel = new javax.swing.JLabel();
        debugDumpLabel = new javax.swing.JLabel();
        objectCountLabel = new javax.swing.JLabel();
        objectCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        layerList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        objList = new javax.swing.JList<>();
        moveSelectedObjBtn = new javax.swing.JButton();
        objsAndLayersLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        drawButton.setLabel("draw");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        clearButton.setLabel("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        randomTriBtn.setText("randomTri");
        randomTriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomTriBtnActionPerformed(evt);
            }
        });

        debugLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        debugLabel.setText("Debug");

        drawLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        drawLabel.setText("Draw");

        debugDumpLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        debugDumpLabel.setText("Debug Dump");

        objectCountLabel.setText("n. of objects");

        objectCount.setText("null");

        layerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(layerList);

        objList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(objList);

        moveSelectedObjBtn.setText("moveSelectedObj");
        moveSelectedObjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSelectedObjBtnActionPerformed(evt);
            }
        });

        objsAndLayersLbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        objsAndLayersLbl.setText("Objs                       Layers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drawButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(debugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveSelectedObjBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(randomTriBtn)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(objsAndLayersLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(debugDumpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(objectCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(objectCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debugDumpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drawButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(objectCountLabel)
                            .addComponent(objectCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(objsAndLayersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(debugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomTriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(moveSelectedObjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed

        frame.repaint();
        System.out.println(renderer.layers.size());

        ArrayList<String> strings = new ArrayList<>();
        ArrayList<String> layers = new ArrayList<>();

        for (Layer layer : renderer.layers) {
            layers.add(layer.toString());
            for (GObject ob : layer) {
                strings.add(ob.getId() + "|" + ob.toString());
            }
        }

        layerList.setListData(layers.toArray(String[]::new));
        objList.setListData(strings.toArray(String[]::new));

    }//GEN-LAST:event_drawButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        renderer.layers.forEach(ArrayDeque::clear);
        frame.repaint();
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void randomTriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomTriBtnActionPerformed

        Random random = new Random();
        int red = random.nextInt(256);   // 0 to 255
        int green = random.nextInt(256);
        int blue = random.nextInt(256);

        Color randomColor = new Color(red, green, blue);

        GTri t = new GTri(randomColor, renderer,
                new GPoint(renderer, new CartesianPoint(ThreadLocalRandom.current().nextInt(-40, 40), ThreadLocalRandom.current().nextInt(-10, 10))),
                new GPoint(renderer, new CartesianPoint(ThreadLocalRandom.current().nextInt(-40, 40), ThreadLocalRandom.current().nextInt(-10, 10))),
                new GPoint(renderer, new CartesianPoint(ThreadLocalRandom.current().nextInt(-40, 40), ThreadLocalRandom.current().nextInt(-10, 10)))
        );
        
//        System.out.println(t.getLegA().getStartPoint());
//        System.out.println(t.getLegA().getEndPoint());
        int tris = 0, lines = 0, pts = 0;
        for (Layer layer : renderer.layers) {
            for (GObject ob : layer) {
                switch (ob) {
                    case GTri tri -> tris++;
                    case GLine line -> lines++;
                    case GPoint pt -> pts++;
                    default -> {
                        ;
                    }
                }
            }
        }
        objectCount.setText("pts: "+pts+" | lines: "+lines+" | tris: "+tris+" | lyrs: "+renderer.layers.size());
        
    }//GEN-LAST:event_randomTriBtnActionPerformed

    private void moveSelectedObjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSelectedObjBtnActionPerformed
        java.util.List<String> selectedValuesList = objList.getSelectedValuesList();
        String selectedLayer = layerList.getSelectedValue();

        for (String  selected : selectedValuesList) {
            String selectedObjId =  selected.substring(0,  selected.indexOf('|'));
            GObject selectedObj = renderer.findObject(selectedObjId);
            Layer selectedLayerObj = renderer.findLayer(selectedLayer);
            renderer.moveObjTo(selectedObj, selectedLayerObj);
        }
        frame.repaint();
    }//GEN-LAST:event_moveSelectedObjBtnActionPerformed

    public static void run(Renderer r, Executor e, Frame f) {
        renderer = r;
        executor = e;
        frame = f;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button clearButton;
    private javax.swing.JLabel debugDumpLabel;
    private javax.swing.JLabel debugLabel;
    private java.awt.Button drawButton;
    private javax.swing.JLabel drawLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> layerList;
    private javax.swing.JButton moveSelectedObjBtn;
    private javax.swing.JList<String> objList;
    private javax.swing.JLabel objectCount;
    private javax.swing.JLabel objectCountLabel;
    private javax.swing.JLabel objsAndLayersLbl;
    private javax.swing.JButton randomTriBtn;
    // End of variables declaration//GEN-END:variables
}
