/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.j3d.ui.help;

import com.j3d.Static;
import com.j3d.gen.docs.J3DocsReader;
import com.j3d.gen.docs.tokens.TLink;
import com.j3d.gen.docs.tokens.TWrapper;
import com.j3d.gen.docs.tokens.wrappers.TWHeader;
import com.j3d.gen.docs.tokens.wrappers.TWLineSeparator;
import com.j3d.gen.docs.tokens.wrappers.TWParagraph;
import com.j3d.utility.generators.JLabelRichText;

import javax.swing.*;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author yetnt
 */
public class HelpFrame extends javax.swing.JFrame {

    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() {
        initComponents();
        try {
            test();
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    private void test() throws FileNotFoundException {
        String some = "pdsdfd ".repeat(20);

        TextPanel p = new TextPanel(
                new JLabelRichText(some)
                        .wrapDiv(400)
                        .heading(JLabelRichText.Heading.H1)
                        .addStyle(
                                new LinkedHashMap<>(
                                        Map.of(
                                                "text-align", "center"
                                        )
                                )
                        )
                        .wrapHTML()
        );
        TextPanel p2 = new TextPanel(
                new JLabelRichText(some.repeat(300))
                        .wrapDiv(400)
                        .wrapHTML()
        );

        jPanel1.add(p);
        jPanel1.add(p2);

        ArrayList<TWrapper> wrappers = J3DocsReader.parseFile(
                Static.getEngineFiles().docsFolder.intro
        );

        JLabelRichText div = new JLabelRichText()
                .wrapDiv(500);
        ArrayList<TLink> linksPerParagraph = new ArrayList<>();

        wrappers.forEach(wrapper -> {
            if (wrapper instanceof TWLineSeparator) {
                jPanel1.add(new TextPanel(
                        new JLabelRichText(JLabelRichText.HORIZONTAL_LINE)
                                .wrapHTML()
                ));
            } else if (wrapper instanceof TWHeader header) {
                jPanel1.add(
                        new TextPanel(
                                JLabelRichText.from(
                                        header.getContent(),
                                        div
                                )
                                        .heading(JLabelRichText.Heading.fromInt(header.getHeaderLevel()))
                                        .addStyle(new LinkedHashMap<>(Map.of(
                                                "text-align", "center"
                                        )))
                                        .wrapHTML()
                        )
                );
                linksPerParagraph.clear();
            } else if (wrapper instanceof TWParagraph paragraph) {
                StringBuilder content = new StringBuilder();
                paragraph.getParagraph().forEach(text -> {
                    if (text instanceof TLink l) {
                        linksPerParagraph.add(l);
                    }
                    JLabelRichText text1 = new JLabelRichText(
                            text.getContent() + (text instanceof TLink ?
                                    "[" + linksPerParagraph.size() + "]"
                            : "")
                    );
                    if (text.isBold()) text1.bold();
                    if (text.isItalic()) text1.italic();
                    if (text.isInlineCode()) text1.wrapTag("code", new LinkedHashMap<>());
                    content.append(text1).append(" ");
                });
                jPanel1.add(
                        new TextPanel(
                                JLabelRichText.from(
                                        content.toString(),
                                        div
                                )
                                        .wrapHTML()
                        )
                );
                // TODO: add links via buttons here at end of paragraph.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Help Menu");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("hi");
        jPanel1.add(jLabel2);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
